### ISSUE TITLE
Save (Ctrl+s) option to save FULL URL as documented in FAQ (not shortened permalink?) 

### ISSUE THREAD

**Issue by dbareis** [firasdib/Regex101#861] opened 2017-06-08 04:46 UTC
If there is a way to decode the links currently created that will do...

But as the FAQ doesn't provide enough information about the format of options (or in any case) it would be great to set things up using the interface and then save the URL required to get back to that stat.

**Comment by Doqnach** [comment] 2017-06-08 06:55
Could you maybe show to what part of the FAQ you are referring? Because I'm not sure what 'Full URL' this would be? Unless you mean the one under point 2, which is no longer supported in the latest version of regex101 and also wasn't kept up-to-date while editing.

You mean you want to bookmark a certain flavour including flags etc, but with empty regex en test string?

**Comment by dbareis** [comment] 2017-06-08 08:07
Hi,

Yes the FAQ point you mentioned is correct, I wanted to let users test
their regular expressions and data in my tool (and perhaps automatically
take them there on syntax errors etc)with an option to use your online tool
after I've transferred the data via the URL.  I have no idea why such an
option would be removed.

Bye,
Dennis

**Comment by Doqnach** [comment] 2017-06-08 14:43
as per the comments on #831 

https://github.com/firasdib/Regex101/wiki/API

This is what is available right now.

**Comment by dbareis** [comment] 2017-06-09 00:32
Thanks, I'll try to work out what that means :-)

**Comment by Zarthus** [comment] 2017-06-15 20:22
the purpose of this ticket is not entirely clear to me, is the issue resolved or does the request still stand?

**Comment by dbareis** [comment] 2017-06-24 08:44
Sorry haven't had time to look into the suggestion, it would certainly not be as easy as what I wanted but appears to be possible.

Basically one way or the other I think I should be able to pass the parameters to the site to prepopulate the form and show the results.  That would be easiest via URL if that was still supported, and if it was then the save option should have allowed for save as URL.

**Comment by TWiStErRob** [comment] 2017-06-24 12:10
@dbareis Your title is a little red herring then. You want to be able to pre-populate the form from url, not create an url from an already popuplated form.

**Comment by Zarthus** [comment] 2017-06-25 16:31
Closing as a duplicate of https://github.com/firasdib/Regex101/issues/872 (although this issue is newer, I find it conveys the idea better)

**Closed by Zarthus** 2017-06-25 16:31 UTC
Labels: waiting info
