### ISSUE TITLE
Substitution Issue while generating code in python

### ISSUE THREAD

**Issue by nitinmlvya** [firasdib/Regex101#324] opened 2015-07-08 13:05 UTC
Using **SUBSTITUTION** on the Regex on *python*, **substitution(\1)** is not working fine. I generate the code. Below is the code:

*Your Code Generator Output:*

```
import re 

p = re.compile(ur'(http:)(.*?)(.org)(ontology|.*)')

test_str = u"http:dbpedia.orgontologySpaceShuttle"

subst = u"\1//\2\3/\4/"

result = re.sub(p, subst, test_str)
```

In **subst** variable, We need to insert **"r"**. So, **subst** variable should be like this **ur"\1//\2\3/\4/"**.
current status =>  ```subst = u"\1//\2\3/\4/"```
suggest status => ```subst = ur"\1//\2\3/\4/"```

Inserting **"r"** into **"subst"**, Issue get solved.

*Expected Code Generator Output:*

```
import re 

p = re.compile(ur'(http:)(.*?)(.org)(ontology|.*)')

test_str = u"http:dbpedia.orgontologySpaceShuttle"

subst = ur"\1//\2\3/\4/"

result = re.sub(p, subst, test_str)
```

Please fix that issue ASAP.

**Comment by firasdib** [comment] 2016-08-22 14:52
@nhahtdh Can you verify if this is relevant in v2?

**Comment by nhahtdh** [comment] 2016-08-23 02:48
Yep, it's still an issue. The safest way to do this is to convert it to normal Python string, rather than raw string, since you can't specify replacement text of `'"` in the raw string.

**Comment by nitinmlvya** [comment] 2016-08-23 04:28
@nhahtdh: Shall I close this issue? Seems that it is resolved.

**Comment by nhahtdh** [comment] 2016-08-23 04:56
@nitinmlvya No, it's wrong in both versions (old and new).

**Comment by firasdib** [comment] 2016-08-23 10:12
@nhahtdh Is this fixed now?

**Comment by nhahtdh** [comment] 2016-08-23 10:14
Confirmed fixed :+1: .

**Closed by nhahtdh** 2016-08-23 10:14 UTC
Labels: bug, code generator, python, waiting info
