### ISSUE TITLE
Regex highlight offset

### ISSUE THREAD

**Issue by Sineaggi** [firasdib/Regex101#489] opened 2016-05-19 00:26 UTC
Using the regex `@\"([^\"]|\"\")*\"` (a c# string literal matcher) causes weird offsets for every subsequent match in [this](https://github.com/OmniSharp/omnisharp-vscode/files/262184/SharedConstants.cs.txt) test file. This issue appears in Chrome Version 52.0.2739.0 dev-m (64-bit), and not in Firefox 46.0.1. I am running Windows 10, x64.
Here is a screenshot of the issue in chrome.
![offset](https://cloud.githubusercontent.com/assets/889237/15379031/fcce1810-1d25-11e6-890f-7eb03da72715.PNG)

**Comment by working-name** [comment] 2016-05-19 00:39
For the sake of making this readily available, I saved it as a URL: https://regex101.com/r/gL4tT9/1

**Comment by grifferton** [comment] 2016-06-13 21:48
I have confirmed this issue on Mac OS X.

Chrome 51.0.2704.84 (64-bit) - offset issue is present (see screenshot)
Firefox 47.0 - match highlighting works properly
Safari 9.1.1 - match highlighting works properly


![online_regex_tester_and_debugger__javascript__python__php__and_pcre](https://cloud.githubusercontent.com/assets/571053/16024228/58c392ac-3186-11e6-9f4e-13a19fe1e16a.png)

**Comment by grifferton** [comment] 2016-06-13 21:53
One other note...resizing the window (and indirectly, the textarea) appears to affect the offset and in some cases (not all) corrects the highlighting.

**Comment by agdfoster** [comment] 2016-06-16 18:39
I have the same issue. Couple weeks back Regex101 became unoperable due to a large offset. I'll click in one place and it clicks somewhere else.

Mac OSX 10.11.4 (15E65) 
Chrome Version 51.0.2704.84 (64-bit)

Problem not there in Firefox

**Comment by firasdib** [comment] 2016-07-03 22:39
Fixed in v2

**Closed by firasdib** 2016-07-03 22:39 UTC
Labels: bug
