### ISSUE TITLE
Test String input box grows unchecked

### ISSUE THREAD

**Issue by MadConan** [firasdib/Regex101#465] opened 2016-04-04 20:18 UTC
Clicking away from the page and/or the input dialog, and then clicking back, "randomly" seems to make the Test String input dialog grow vertically until it moves the substitution input field off the page.  No scroll bars appear so it makes the substitution input field inaccessible. 

Browser:  Chrome 49.0.2623.110 (64-bit)
OS:  Mac OS X 10.9.5

**Comment by OnlineCop** [comment] 2016-04-04 20:45
Duplicate of #456 and #423.

**Closed by OnlineCop** 2016-04-04 20:45 UTC
