### ISSUE TITLE
Add "Each line is a separate input" mode

### ISSUE THREAD

**Issue by tustin2121** [firasdib/Regex101#359] opened 2015-09-01 20:10 UTC
It would be nice if there was a flag or mode where each line in the test string box is considered a completely separate input. 

I like to test my regexes against multiple inputs at once to see if it matches all the cases I'm considering, and very rarely am I going to be using my regex against a multiline string in the field. I can get close to what I want by applying the `gm` flags, but regexes like `/([^,]+),/` will still match over the newline in this mode.

**Comment by jemery27** [comment] 2015-09-01 23:41
Can't you just set the flag g to show all matches? That way it will highlight all matches on all lines for validation.

Global modifier: g
Tells the engine not to stop after the first match has been found, but rather to continue until no more matches can be found.

**Comment by tustin2121** [comment] 2015-09-01 23:54
That's what I have been doing, as I said. I've been using the `g` and `m`
flags to get as close as I can, but there are subtle differences between
this and treating each line as a separate input.

Sure, dot operators don't match new lines. But basically any matching using
negated character sets `[^\w]` will match on a new line, and I really
shouldn't have to make my regexes do things to fit this tool for cases that
will never appear in production due to code around the regex splitting
lines and such.

Hence my feature request.

**Comment by nhahtdh** [comment] 2015-09-07 09:53
The modes are defined by the languages. Not sure, but you might want to try the unit test feature?

**Comment by anthonyattard** [comment] 2015-09-17 21:15
I second this request.

**Comment by tustin2121** [comment] 2015-09-18 15:18
@nhahtdh I was unaware of the Unit Tests feature. It does perform the same function as requested, but it is extremely clunky to use: 

- Once a unit test is made, it can't be edited, not even to switch "matches" and "does not match".
- You can't copy in a blob of text, like say from a file you will be parsing; you have to enter tests one line at a time.
- It doesn't highlight the matched groups like the test string box does. Nor does it give match information.
- Unlike the test string box, you have to manually start the unit tests.

I'm not saying the requested feature *has* to be a mode modifier. Perhaps its better as a switch or checkbox on the "test string" header, like the regex version selector is for saved regexes.

**Comment by fnkr** [comment] 2015-10-06 13:02
I'm missing test editing/reordering too and created an issue for that (#375).

**Comment by mattdodge** [comment] 2015-10-13 22:40
:+1: 

The reason the `/g` flag won't work, at least in my case, is because you can't use the start-of-string `^` or end-of-string `$` to match.

Adding a setting for "treat each line as new input" would solve it, but I'm unsure of the complexity of adding such a feature.

**Comment by nhahtdh** [comment] 2015-10-15 03:18
@mattdodge It's actually `m` flag (which is available in many regex flavors), but that won't work well with a pattern that already has `m` flag.

**Comment by mattdodge** [comment] 2015-10-15 17:54
@nhahtdh Ah, you are totally right! I don't know why I didn't think of using the `m` flag. That actually solves the use case that I had originally, but I could still envision use cases where the `gm` flags wouldn't be sufficient. An option to "ignore new lines" would maybe cover everything, but I'm not sure what the desired behavior would be to have that option enabled and also an `m` flag. I do think this is a trickier issue than I originally thought now.

**Comment by fnkr** [comment] 2015-10-15 20:21
I use `/gm` all the time but it's quite useless if your test strings actually have multiple lines and you need `^` and `$` to match the beginning/end of the whole string, not just the line.

**Comment by holroy** [comment] 2015-10-28 02:44
It would be great to test against multiple lines as separate inputs. In this regex text:  https://regex101.com/r/gU9eV7/3, I resorted to using unit tests, and it uses multiline texts. But it would be great to include both in the main test window as two (or more) separate text inputs.

**Comment by OnlineCop** [comment] 2016-02-09 23:09
ReSharper has a "Check lines separately" mode similar to this. http://i.imgur.com/Ayvoesl.png Interesting that they simply "reuse" a multi-line "Test Input" box that would otherwise be considered all part of the same string.

**Comment by maxstarkenburg** [comment] 2016-05-03 13:22
I second this, or a variation I had in mind before seeing this request. 
- My use case: I have one string that works, with matches in hard-to-visually-track places, and another string that doesn't work. Would like to be able to simultaneously test them without constant cutting/pasting one then the other.
- My though for the UI: I had originally conceived a "+" or something to add a second (or multiple subsequent) TEST STRING textboxes. Of course, this wouldn't work for the OP's desire to paste in multiple lines at once.

**Comment by Gyomo** [comment] 2016-08-04 00:25
+1 ( just for the ^$ use case)

**Comment by firasdib** [comment] 2016-08-22 21:52
Duplicate of https://github.com/firasdib/Regex101/issues/282

As for the unit test complains, the new version features a much improved version of it.

**Closed by firasdib** 2016-08-22 21:52 UTC
Labels: enhancement, feature request
