### ISSUE TITLE
Little bug - SUBSTITUTION BOX

### ISSUE THREAD

**Issue by JhonhSilva** [firasdib/Regex101#515] opened 2016-07-20 16:31 UTC
Is possible write in substitution textbox when the SHIFT key is holding

**Comment by nhahtdh** [comment] 2016-07-21 02:33
I have a hard time understanding what you are trying to report here. Do you mean that you cannot type anything into the substitution textbox when you are holding SHIFT key? If that's the case, what is the browser and OS?

**Comment by OnlineCop** [comment] 2016-07-21 03:21
Duplicate of #303.

**Closed by OnlineCop** 2016-07-21 03:21 UTC
Labels: waiting info
