### ISSUE TITLE
Does not has support for ungreedy solution in python

### ISSUE THREAD

**Issue by BinaryBlackhole** [firasdib/Regex101#1247] opened 2019-11-19 15:24 UTC
## Bug Description
Could not stop the iteration of searching last pattern even if it has found one.

### Reproduction steps
([0-9]{1,} .+.* .+, .* [0-9]{5,10})
PROPERTY ADDRESS 625 S 125 LnW Rupert, ID 83350,sdvbsdo dssadvd ID 1245 WQEUEFVGIUSD VDH SAHD90QWGDVGQWD BSDAHXB SD DSB VASDzAWGDUSADSADG ASD GSADADSOA

### Expected Outcome
625 S 125 LnW Rupert, ID 83350

### Browser
Include browser name and version
mozilla firefox

### OS
Include OS name and version
win10

**Comment by Doqnach** [comment] 2019-11-20 08:41
https://regex101.com/r/OULrUt/1

![image](https://user-images.githubusercontent.com/25537191/69222456-d1618900-0b79-11ea-8ce1-efdd79234e2b.png)

Working as intended and matches your expected outcome... so not sure what the problem is here?

Also, your regex has no ungreedy anywhere? So also unsure how the title of the issue matches with the described problem.

PS: No need to do it in all caps...

**Comment by working-name** [comment] 2019-12-03 15:31
Thank you everyone, closing for now. Please reopen if deemed necessary.

**Closed by working-name** 2019-12-03 15:31 UTC
Labels: bug
