### ISSUE TITLE
New dark theme has insufficient contrast between text and background

### ISSUE THREAD

**Issue by wmcb91** [firasdib/Regex101#1458] opened 2020-12-29 19:27 UTC
## Bug Description
Since the theme update (which looks great other than the issue I'm describing), most of the text on the website has insufficient contrast with the background. This is an accessibility issue for your users. WCAG 2.0 level AA requires a contrast ratio of at least 4.5:1 for normal text. If you run [Lighthouse](https://developers.google.com/web/tools/lighthouse) on the website it will list all failing elements for you. 

### Reproduction steps
Visit the website in dark mode

### Expected Outcome
Text 

### Browser
Chrome 87.0

### OS
macOS Big Sur 11.0.1

### Solution
Here is an overview of some of the contrasts on the site that are most noticeable at first glance:
1. The left side bar items have a contrast ratio of 4:1.
2. The quick reference items have a ratio of 3.79:1.
3. The match group range in the match information as a contrast of 2.25:1
4. The "An explanation... as you type" and "Detailed match information... automatically." text has a ratio of 1.69:1
5. The CodeMirror-placeholders have a contrast ratio of 2.64:1

I took a look at the colors in use and have provided the colors that would make the elements meet contrast standards:

- To solve items 1 & 2, it looks like changing `$dark_listMenu_defaultContent_button_color` from `#797979` to `#868686` would get you a 4.5:1 ratio and changing it to `#a9a9a9` would get you the 7:1 ratio for level AAA (recommended).
- To solve item 3, changing `$dark_matchGroup_pos_color` from `#565656` to `#868686` would get you 4.5:1 contrast.
- To solve 4, changing `$dark_rightSidebar_placeholder_color` from `#333333` to `#868686` would get you 4.5:1 contrast.
- To solve 5, changing to from `#676767` to `#8e8e8e` in the `.dark .CodeMirror-placeholder` class would get you 4.5:1 contrast.

I hope this helps! I really appreciate all the work you put into the website. It has been great resource for me so I just want to make sure everybody can use it.

**Comment by firasdib** [comment] 2021-01-01 18:19
Thanks for your thorough report!

I realize some of the element need a bump in contrast, but I'm not entirely sure if the dark theme should be bumped to the level you suggested. I personally enjoy dark themes with a low contrast, but I understand this does not fit everybody.

**Comment by minig0d** [comment] 2021-01-12 20:31
Agree with the OP, I use dark theme across the board but looking at the page now is so dim it's illegible.  (And a lot of devs run our monitors with pretty low brightness to begin with to reduce eye strain.).  I just quickly pulled up a handful of dev sites I visit with dark themes (ex. caniuse.com) and even though their overall theme is dark, their text actually is over 7:1

If you look into the underlying concepts behind those numbers, the 4.5 contrast ratio isn't just intended to make it accessible for someone with impaired vision, it's that even for people with "normal" vision, contrast that low can create eye strain and so it shouldn't be used on anything other than decorative elements (i.e. should never be that low on navigation or text intended for reading.

I agree some dev's may not like the #a9a9a9 7.0 contrast ratio which is really needed to make the site usable for people with vision issues, but I can't see much pushback in changing the corresponding 4.5 ratio colors the OP suggested.  Please update to at least the 4.5 while pondering how to address it.

Can always make an ultra dark theme or one of those things where users can paste their own stylesheet into a textbox, but those are really niche cases, the vast majority of people just want something somewhat dark so it doesn't burn our eyes.  I was about to just leave the site back on light mode or make a tampermonkey script just to fix the issue is how bad it is right now :(

**Comment by firasdib** [comment] 2021-01-12 21:10
Alright, I understand your frustration. Could you modify the colors as you see fit and report back to me like OP did? I will try them out and take it from there, it would save a lot of time, and I am swamped with the big update that's upcoming.

**Comment by working-name** [comment] 2021-01-13 00:07
I get why this is important for the aforementioned demographic but I'm quite a fan of the current contrast. If it doesn't create yet more work for you, I would appreciate a switch in user preferences to use the current dark theme vs whatever is coming next :)

**Comment by minig0d** [comment] 2021-01-13 00:10
Sorry, its a bit tricky to test these due to the layout of the page breaking the accessibility inspection tools... and the SCSS giving me a headache going back and forth between screens... but I think these few tweaks should fix the majority of them (and as you can see, they are all super close so I doubt anyone will notice (except in a positive way).  I can re-check it after updated and see if any were missed.. Find >replace:
background-color:
#457ABB > #4377B6

color:
#797979 > #868686
#444 > #868686
#4a4a4a > #868686
#33804d > #3C975a
#6f6f6f > #7d7d7d
#a03b3b > #cd6060
#36577d > #5385bf
#364 > #4f9e69
#885d5d > #b97f7f
#36577F > #578dcd
#545454 > #808080
#565656 > #8e8e8e

#ababab > #9e9e9e // this one is actually relatively really light on the Library page this change darkens it a little (but may break somewhere else

**Comment by minig0d** [comment] 2021-01-13 02:12
> I get why this is important for the aforementioned demographic but I'm quite a fan of the current contrast. If it doesn't create yet more work for you, I would appreciate a switch in user preferences to use the current dark theme vs whatever is coming next :)

Have you tried the colors suggested?  I really doubt you'll find them significantly different... definitely not enough so to warrant a separate theme.

**Comment by working-name** [comment] 2021-01-13 18:10
> Have you tried the colors suggested? I really doubt you'll find them significantly different... definitely not enough so to warrant a separate theme.

Have not, but if the contrast ratio is incremented minimally, won't that still fall short of the recommended ratio?

**Comment by firasdib** [comment] 2021-01-13 18:16
Here is a comparison of the proposed changes.

Old

<img width="1680" alt="Screenshot 2021-01-13 at 19 08 57" src="https://user-images.githubusercontent.com/1335165/104492356-ca92a280-55d3-11eb-9d42-cb6466f64290.png">

New

<img width="1680" alt="Screenshot 2021-01-13 at 19 14 16" src="https://user-images.githubusercontent.com/1335165/104492364-cfefed00-55d3-11eb-92ab-719dea16391d.png">


It needs a few tweaks, but could be viable. It feelt brighter, for sure.

**Comment by minig0d** [comment] 2021-01-13 19:55
> Here is a comparison of the proposed changes.
> 
> Old
> 
> <img alt="Screenshot 2021-01-13 at 19 08 57" width="1680" src="https://user-images.githubusercontent.com/1335165/104492356-ca92a280-55d3-11eb-9d42-cb6466f64290.png">
> 
> New
> 
> <img alt="Screenshot 2021-01-13 at 19 14 16" width="1680" src="https://user-images.githubusercontent.com/1335165/104492364-cfefed00-55d3-11eb-92ab-719dea16391d.png">
> 
> It needs a few tweaks, but could be viable. It feelt brighter, for sure.

Definitely much more legible, but something looks weird... I could be wrong but it also looks like between your first and second screenshot, not just the colors changed, but the font and font-weight changed too? Not familiar with Monaco font but guessing it's a Mac one... Mine is rendering in consolas which definitely looks thinner (lower weight) than yours which definitely makes it harder to read at the lower contrast ratio.

But it also looks like something changed between yesterday and today too?  Were any of the changes pushed out? (Looks a bit easier to read today but below is what I'm seeing)

Assuming your bottom screenshot accurately reflects the above changes, It doesn't look too bad.  The greens distinctly stand out  and can probably get toned down a little bit, but I'd also worry about losing contrast on those smaller elements, so possibly just that one in the upper right needs to be on it's own class.  (See second annotated screenshot). 

Hard to tell without seeing it all together but changing that green in the upper right from #364f47 (original color) > #1c542f
would probably tone it down a bit

One other last thing worth noting is that everyone (of course) has different preferences (especially in the coding arena).  So, I'm really not suggesting that the changes will make people who prefer the "darkest of dark" themes happy, and it surely won't please the people who like "grey" themes happy, I'm shooting for functional (for someone with normal vision) and relative to other dev oriented sites with dark themes (especially since I know you're busy with much more important things).  In reality, it would be great if the site were fully accessible for our vision impaired friends, but that's likely a much longer discussion.  With careful color choices you can achieve 7:1 with a dark theme (ex. https://caniuse.com/)

// Ex of what I'm seeing (confirmed it is rendering in Consolas):
![2021-01-13_13h24_12](https://user-images.githubusercontent.com/54046315/104499389-a5d20700-55a2-11eb-957d-e6be7509cf53.png)

// Drawing on your screenshot:
![image](https://user-images.githubusercontent.com/54046315/104501055-d61aa500-55a4-11eb-8598-146e72c8626b.png)

**Comment by firasdib** [comment] 2021-01-24 21:53
How are you liking the new update? Can this be closed?

**Comment by minig0d** [comment] 2021-01-25 01:59
> How are you liking the new update? Can this be closed?

Looks great to me... My eyes thank you!  Of course, I kind of hijacked the OP's issue so I can't speak for him :)

**Comment by firasdib** [comment] 2021-01-25 17:49
Great. Closing for now :)

**Closed by firasdib** 2021-01-25 17:49 UTC
Labels: enhancement
