### ISSUE TITLE
Where have the rest of the JS flags gone?

### ISSUE THREAD

**Issue by ghost** [firasdib/Regex101#2240] opened 2024-03-11 18:56 UTC
## Bug Description

`[\u{1D7FF}|\u{1D7FC}|\u{1D7FE}]`
Now I can’t use this construction in JS

![image](https://github.com/firasdib/Regex101/assets/16405504/92b43287-6e08-45fd-8b83-f376926cd06e)

**Comment by working-name** [comment] 2024-03-19 16:01
Hello @program23 

I think your browser _et em_. 😃 I would try loading the page in an incognito window or another browser. If that's still the case, then regex101 is croaking. So far I can't reproduce this across 4 OSes and many browsers.

**Comment by firasdib** [comment] 2024-03-19 18:43
This was a bug, it's fixed. I forgot to comment and close the issue :)

**Closed as completed by firasdib** 2024-03-19 18:43 UTC
Labels: bug, no repro
