### ISSUE TITLE
Export  Without  FullMatches

### ISSUE THREAD

**Issue by txh0001** [firasdib/Regex101#1267] opened 2020-01-09 03:48 UTC
## Feature
when export matches ，user can choose export fullmatches or just group,or both of

**Comment by Doqnach** [comment] 2020-01-09 08:37
Duplicate of #1063, #792 
Related to  #1062

**Comment by firasdib** [comment] 2020-02-01 09:25
Due to popular demand I've implemented this. Lets see how it plays out.

**Closed by firasdib** 2020-02-01 09:25 UTC
Labels: duplicate, enhancement
