### ISSUE TITLE
Infinite redirect loop in google login 

### ISSUE THREAD

**Issue by mbarkhau** [firasdib/Regex101#466] opened 2016-04-05 11:59 UTC

**Comment by mbarkhau** [comment] 2016-04-05 12:00
I hope this is easily reproducible for others, otherwise I'll add more info.

**Comment by LeightonSmallshire** [comment] 2016-04-05 23:42
I am having the same problem. I cannot login through Github either.

**Comment by LeightonSmallshire** [comment] 2016-04-05 23:43
I am having the same problem. I cannot login through Github either

**Comment by Zarthus** [comment] 2016-04-06 17:42
I'm not able to reproduce. Can you tell me which browser you are using and if there are any errors in the console?

**Comment by firasdib** [comment] 2016-04-25 17:21
This is fixed now, and will be permantently fixed in the new version.

**Closed by firasdib** 2016-04-25 17:21 UTC
Labels: bug
