### ISSUE TITLE
#Engine Error

### ISSUE THREAD

**Issue by milan1750** [firasdib/Regex101#1288] opened 2020-02-11 06:04 UTC
## Bug Description
Engine Error

Once it says engine error, We have to reload the page! any way to get rid of reloading the page?
### Browser
Include browser name and version
Chrome Latest
### OS
Include OS name and version
Ubuntu

**Comment by firasdib** [comment] 2020-02-11 06:06
Please provide reproduction steps. 


Vänliga hälsningar / Best regards,

Firas Dib

**Comment by milan1750** [comment] 2020-02-11 06:07
The Size of text is 12MB. Is that an issue?

**Comment by firasdib** [comment] 2020-02-11 06:08
That sounds like a lot, maybe. Try with less. 


Vänliga hälsningar / Best regards,

Firas Dib

**Comment by milan1750** [comment] 2020-02-11 06:10
Thanks, But i wish you would solve the page idol problem once there's an issue occurred.

**Comment by firasdib** [comment] 2020-02-11 06:11
As I said, please provide steps to reproduce the issue. 


Vänliga hälsningar / Best regards,

Firas Dib

**Comment by milan1750** [comment] 2020-02-11 06:15
![Screenshot from 2020-02-11 11-59-27](https://user-images.githubusercontent.com/34101157/74214569-0a675080-4cc6-11ea-8c80-957054ec2ed4.png)
![Screenshot from 2020-02-11 11-59-16](https://user-images.githubusercontent.com/34101157/74214570-0b987d80-4cc6-11ea-866a-e0374c6264be.png)

**Comment by firasdib** [comment] 2020-02-11 06:16
Save the regex and give me the link please. 


Vänliga hälsningar / Best regards,

Firas Dib

**Comment by milan1750** [comment] 2020-02-11 06:16
https://regex101.com/r/nqSSUV/1

**Comment by firasdib** [comment] 2020-02-11 06:19
The link works just fine for me. 


Vänliga hälsningar / Best regards,

Firas Dib

**Comment by milan1750** [comment] 2020-02-11 06:20
it works once reloading the page, i m asking can you fix its idleness once there is an engine err.

**Comment by firasdib** [comment] 2020-02-11 06:27
You need to provide steps for me to reproduce the engine error. 


Vänliga hälsningar / Best regards,

Firas Dib

**Comment by milan1750** [comment] 2020-02-11 06:30
1. Paste Huge text on the text area

2. Implement any regex Rule
    Then it will cause Engine Error

4. Remove that huge text from text Field

5. Add some text to text area.

6. implement any regex rule.

**Comment by working-name** [comment] 2020-02-13 06:40
I can’t crash my chrome with these steps. Are you running a vanilla install - aka no addons, just the way it comes from its ABC mother? Also which version of Ubuntu and window manager? I can try to mirror your setup in a VM or a laptop.

**Comment by firasdib** [comment] 2020-03-08 10:45
Closing since we cant reproduce.

**Closed by firasdib** 2020-03-08 10:45 UTC
Labels: bug
