### ISSUE TITLE
A critical error has occurred

### ISSUE THREAD

**Issue by Wind010** [firasdib/Regex101#2062] opened 2023-05-15 03:32 UTC
## Bug Description
A critical error has occurred when pasting a long string into Test string textbox.  Possibly same issue with the Patten box.

### Reproduction steps

1.  Select ECMAscript Flavor
2.  Use pattern `/\p{Emoji}/u`, but I suspect any simple pattern will reproduce it.
3.  Continually copy a long string into the the Test string textbox.

### Expected Outcome
There should be limit to the Test string and the page should not crash.

Console log:
```sh
Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at i.lineInner (vendors-bundle.c49ab84005e4d8d9f85a.js:2:346139)
    at i.lineAt (vendors-bundle.c49ab84005e4d8d9f85a.js:2:344557)
    at fn.blockAt (vendors-bundle.c49ab84005e4d8d9f85a.js:2:461831)
    at xn.elementAtHeight (vendors-bundle.c49ab84005e4d8d9f85a.js:2:479073)
    at $n.elementAtHeight (vendors-bundle.c49ab84005e4d8d9f85a.js:2:507751)
    at Mt (vendors-bundle.c49ab84005e4d8d9f85a.js:2:439709)
    at $n.posAtCoords (vendors-bundle.c49ab84005e4d8d9f85a.js:2:509495)
    at bundle.afaefc6ee24c1d714907.js:1:338347
    at bundle.afaefc6ee24c1d714907.js:1:338568
    at bundle.afaefc6ee24c1d714907.js:1:339442
    at i (vendors-sentry.6fea3ab873d9298d6dd5.chunk.js:1:29403)
```

### Browser
Chrome Version 113.0.5672.64 (Official Build) (64-bit)

### OS
Microsoft Windows [Version [10.0.19044.2846]]([url](url))

![image](https://github.com/firasdib/Regex101/assets/17187851/380b74e7-d7d3-4e1a-97f5-0c1e252cc5af)

**Comment by firasdib** [comment] 2023-05-15 10:42
I am unable to reproduce this. Can you show a video or something?

**Comment by Wind010** [comment] 2023-05-15 22:29
Sure, note that the string copied was just a random generated string from alpha-numeric character set: 
 `abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789`

https://github.com/firasdib/Regex101/assets/17187851/6fadbf81-5c21-4541-9907-4d79b82f6aa7

**Comment by firasdib** [comment] 2023-05-16 09:35
This looks like a bug in CodeMirror.... It seems it cannot handle that large texts for some reason.

**Comment by firasdib** [comment] 2023-08-12 15:38
Can this still be reproduced?

**Comment by DingJC17** [comment] 2023-09-15 03:21
I also encountered this issue while copying long text
![image](https://github.com/firasdib/Regex101/assets/57793122/0efe187c-9c5e-429e-b71b-1d3741a1502e)

**Comment by firasdib** [comment] 2024-05-18 18:59
Anyone run into this again?

**Comment by firasdib** [comment] 2024-09-16 15:08
Closing for now, please reopen if it happens again.

**Closed by firasdib** 2024-09-16 15:08 UTC
Labels: bug, upstream
