### ISSUE TITLE
In Python, '\d' match unicode digit cannot display correctly.

### ISSUE THREAD

**Issue by A-hoy** [firasdib/Regex101#1214] opened 2019-10-19 02:27 UTC
## Bug Description
In Python, '\d' can match unicode digit correctly, but cannot display correctly.

### Reproduction steps
REGULAR EXPRESSION: '\d+'
TEST STRING: '123߅߆߇߈'

### Expected Outcome
display full match

### Browser
Yandex 19.9.3.314

### OS
Windows7 32-bit

### User-Agent
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 YaBrowser/19.9.3.314 Yowser/2.5 Safari/537.36

**Comment by A-hoy** [comment] 2019-10-19 02:28
![re_unicode_num](https://user-images.githubusercontent.com/55936555/67136611-2c425080-f25b-11e9-95d9-61e4956dd3c6.png)

**Comment by Doqnach** [comment] 2019-10-21 07:12
I am unable to reproduce this issue because copy & pasting the above number string gets malformed for me.

Please provide a regex101 link showcasing this issue.

**Comment by A-hoy** [comment] 2019-10-21 07:24
@Doqnach 
https://regex101.com/r/FsJ8Tg/1

**Comment by Doqnach** [comment] 2019-10-21 07:31
Ah! This comes back to display issues with RTL characters I think, which is actually an upstream bug (codemirror).

See #789, #341

**Comment by firasdib** [comment] 2019-10-30 20:06
Yep, same old codemirror bug...

**Comment by verdy-p** [comment] 2020-04-23 08:17
I confirm: in this test, the string is entirely made of digits (three LTR digits and three RTL digits), so \d+ matches the whole text which has bidirectional content.

But the colored presentation of the match is incorrect as it emphasizes only the first three LTR digits and the last RTL digit.

Apparently, to colorize the matches in the input text, the text if first parsed for "runs" in the same resolved Bidi direction, so it is first broken in two runs, the leading 3 LTR digits and the ending 3 RTL digits

Then each run is colorized separately according to the start/end position of matches in the whole text,

But the colorized runs must preserve their original encoding order. This is not the case here; to colorize each run, just surround the resolved unidirectional runs with <bdi>...</bdi> and colorize the match parts using <span style="...">...</span>.

**Comment by firasdib** [comment] 2021-01-17 09:48
Fixed in the upcoming update! Expect it in the coming weeks.

<img width="485" alt="Screenshot 2021-01-17 at 10 48 00" src="https://user-images.githubusercontent.com/1335165/104836915-7b898d80-58b1-11eb-8a9d-c5705112f9d3.png">

**Closed by firasdib** 2021-01-17 09:48 UTC
Labels: bug, upstream
