### ISSUE TITLE
Blurry text on zoom in chrome

### ISSUE THREAD

**Issue by tarreislam** [firasdib/Regex101#666] opened 2016-09-29 10:48 UTC
If you are at any other zoom than 100% the flags-box will get blurry

http://imgur.com/a/g5FtS

Edit:
Chrome `53.0.2785.116 m`
Microsoft Windows 7 [Version 6.1.7601] 64 bit
And It was not affecting IE, my bad!

**Comment by firasdib** [comment] 2016-09-29 13:39
Sounds like a font rendering issue on your end. It could be that specific combination of zoom and the font size you have selected on your system does not mix well? I can not reproduce on Chrome 53 on OSX.

Does it remain blurry if you close and reopen it? Is anything else affected in a similar way? What OS is this?

**Comment by TWiStErRob** [comment] 2016-09-29 14:35
Chrome 53 Windows 10 reproes.
Anything other than 100%, 200%, 300% is really blurry. 150% is acceptable, but still blurry.
The weird thing is that other text on the page looks ok.

I played around a little in dev tools the problem is two-fold:
 * `tether-element` has `translateZ(0px)`
 * `_23v1ch5eFVw9WC3xHk91J6` has `z-index: 1003`

If either of those is enabled alone, it gets blurry. If neither, then ok.

**Comment by TWiStErRob** [comment] 2016-09-29 14:46
Played with a lot of solutions for `"translatez blurry"`, but non seems to have fixed it. Only removal helps.

**Comment by tarreislam** [comment] 2016-09-29 14:48
@firasdib thats strange, I am using 53.0.2785.116 m

**Comment by TWiStErRob** [comment] 2016-09-29 14:48
@tarreislam which operating system?

**Comment by tarreislam** [comment] 2016-09-29 14:50
@TWiStErRob Microsoft Windows 7 [Version 6.1.7601] 64 bit

**Comment by TWiStErRob** [comment] 2016-09-29 14:53
I can reproduce in IE11 too, turning off z-index alone helps there if you change the zoom level right after disabling it. This suggests to me that it would work if z-index wasn't there in the first place.

**Comment by TWiStErRob** [comment] 2016-09-29 14:55
Edge 25 is affected too.

**Comment by firasdib** [comment] 2016-09-29 15:13
@TWiStErRob Can you pop on IRC and we can have a quick debug session? I can not reproduce in my VM.

**Comment by TWiStErRob** [comment] 2016-09-29 21:26
Here's an isolated repro for Chrome: https://jsfiddle.net/TWiStErRob/ksfoqowt/4/
Corresponding bug report: https://bugs.chromium.org/p/chromium/issues/detail?id=651580

**Comment by firasdib** [comment] 2018-12-24 01:55
This seems to still be an issue, and since I can't do anything to solve it, I'll close this issue.

**Closed by firasdib** 2018-12-24 01:55 UTC
Labels: UX, bug, upstream
