### ISSUE TITLE
Un-Format regex

### ISSUE THREAD

**Issue by Enissay** [firasdib/Regex101#233] opened 2015-02-07 11:58 UTC
While building a regex the `format regex` option can be usefull. But, it would be great to add the opposit function that produces a one line regex to use inside the code.

Yes, i could use a regex to remove the extra spaces but why not to implement this, I think it's axiomatic to do so, isnt it ?

**Comment by firasdib** [comment] 2015-02-09 14:12
Sure, it's possible I suppose - but not sure if its worth it. I see a lot of potential edge cases that would be a headache.

**Comment by firasdib** [comment] 2015-03-22 14:38
In fact, when I think about it, when you format the regex, it is a destructive action. You can in other words not go back to the exact same regex you had prior. This would of course mean that it would only work with `x`-flag enabled. Not sure what I feel about it, but I will leave this issue open.

**Comment by firasdib** [comment] 2015-03-22 16:42
I will mark this as duplicate of #142

**Closed by firasdib** 2015-03-22 16:42 UTC
Labels: feature request, low prio
