### ISSUE TITLE
Preview a sed/vi-style replacement

### ISSUE THREAD

**Issue by roblevy** [firasdib/Regex101#399] opened 2015-11-18 14:04 UTC
Love the site! It's my new favourite thing.

It'd be amazing if I could also preview `sed`-style replacements of the form:

```
> echo "How does this look now?" | sed 's/[A-Z]*[a-z]*/& &/g'
How How does does this this look look now now? 
```

**Comment by nhahtdh** [comment] 2015-11-20 04:36
sed and vi has their own regex and replacement string syntax, so it's best if the whole flavor is supported rather than mixing the syntax and engines.

**Comment by Zarthus** [comment] 2017-03-30 20:59
Duplicate of https://github.com/firasdib/Regex101/issues/196

**Closed by Zarthus** 2017-03-30 20:59 UTC
Labels: duplicate, flavor request
