### ISSUE TITLE
(?!) is explained as "negative lookbehind", when it is actually a "negative lookahead"

### ISSUE THREAD

**Issue by tbdksi** [firasdib/Regex101#1772] opened 2022-04-06 10:15 UTC
## Bug Description

When you have a regex with `(?!)` in it, if you hover your mouse over it or look in the "Explanation" part, it is stated that it is a negative lookbehind. But `(?!)` is a negative lookahead according to the Quick Reference, this [Stackoverflow](https://stackoverflow.com/questions/2973436/regex-lookahead-lookbehind-and-atomic-groups), et cetera.

![image](https://user-images.githubusercontent.com/99797767/161952647-fbd37f10-2688-4526-9a45-45cd68facaf9.png)
![image](https://user-images.githubusercontent.com/99797767/161952707-1cc68b3e-a1b0-47a5-b5fd-a86aa0609375.png)

### Reproduction steps

1) Go to [https://regex101.com/](https://regex101.com/)
2) Choose any flavor
3) Write a regex that contains `(?! ... )` in it. `(?!)` will suffice.  
4) Observe that it says "negative lookbehind"

### Expected Outcome

That the explanation says "negative lookahead"

### Browser
Firefox Nightly 101 64-bit

### OS
Win10

**Comment by working-name** [comment] 2022-04-06 12:19
Thank you! Closing as duplicate of #1768 - it will be addressed in the next update.

**Closed by working-name** 2022-04-06 12:19 UTC
Labels: bug, regression, UX, duplicate
