### ISSUE TITLE
Python unicode escapes do not work at all.

### ISSUE THREAD

**Issue by ztane** [firasdib/Regex101#209] opened 2015-01-12 13:53 UTC
[This regex](https://regex101.com/r/oC1bN5/1) -  `([\u0028-\u0029]+)` probably ought to behave like `([()]+)`, as we are led to believe that `\u` escapes work, however the regex behaves equivalent to `([028-\\]+)`.

(Also python 2 and python 3 regexes behave differently in this regard.)

**Comment by nhahtdh** [comment] 2015-01-13 08:16
@ztane: The behavior in regex101 is correct and reflects the behavior of Python 2.* and Python 3 up to [Python 3.2](https://docs.python.org/3.2/library/re.html).

A small correction - the resulting regex is equivalent to `[028-u]`.

`\u` and `\U` are only supported from [Python 3.3](https://docs.python.org/3.3/library/re.html) and above, where I agree that it would be nice if there is some sort of option to select the version.

**Comment by ztane** [comment] 2015-01-13 10:50
Yes, but the syntax highlighting shows "\u" as an unicode escape there, also unicode escapes do not work at all in 8-bit string expressions; you need ur'' for that in python 2 - the " " around the box also add to the confusion (shouldn't it be r" " if that is the syntax used).

Also considering that Python 3 has been out for ages, and Python 3 being the python where the new development occurs, then Python 3 support would be the way to go. ;-)

**Comment by ztane** [comment] 2015-01-13 10:54
And indeed, 8-u it is, I didn't even check as I remembered `ord(r'\')` incorrectly

**Comment by nhahtdh** [comment] 2015-01-13 12:00
The thing is `\u` is interpreted as match character `u`, so `8-\u` is actually `8-u`

**Comment by firasdib** [comment] 2015-01-19 14:14
So the problem is rather that `\u` is being highlighted incorrectly?

**Comment by nhahtdh** [comment] 2015-01-20 08:39
@firasdib: The current implementation is correct according to Python 2 (tested with 2.7) and Python 3 (up to version 3.2).

However, from Python 3.3, `re` package starts to support `\uhhhh` and `\Uhhhhhhhh` causes the regex above to behave differently.

**Comment by nhahtdh** [comment] 2015-01-20 16:58
@firasdib: Now I understand what the problem is now... There is a mismatch between the regex tester interface and the code generator section.

### Unicode escape sequence in string literal

In the regex tester interface, you are currently taking everything in verbatim, and the string is place inside `ur"..."` in the code generator with the expectation that you are creating a Unicode string, and the string ends up as the same the string from the interface.

While it is true for raw string (Python 2 `"..."`, Python 3 `br"..."`) where only `\\` and `\"` are considered special sequences and interpreted literally, it is not the case for Unicode raw string.

In Unicode raw string (`ur"..."` in Python 2 and `r"..."` in Python 3), the Unicode escape sequences `\u` are always resolved into the corresponding character.

This causes a mismatch between what is shown in the interface and code generator. Given the string `[\u0028-\u0029]` in the regex interface, the code generator generates the string `[(-)]`.

I have some ideas to make them consistent, but they are not pretty:
1. One way is to allow user to choose different ways to specify string (`ur"..."`, `br"..."`, `b"..."`, `u"..."`) from the interface, and regex101 includes the algorithm to parse Python string literal. Quite a lot of work to be done here, and not exactly easy to make a good interface.
2. The second way is to detect **valid** Unicode escape sequences and escape the `\` in the code generator. The downside is that users are forced to enter the actual character instead of Unicode escape sequence, which is not convenient for special characters and space characters.
3. (See below) Screw support for Python 2 and Python 3 version prior to 3.3. Use engine from Python 3.3 and advertise it as Python. The actual regex in the tester and the regex in the code generator are mismatched, but compile to the same thing.

### Unicode escape sequence in regex

To add to the confusion, `\u` escape sequence at regex level is only available from Python 3.3. Earlier version of Python 3 and Python 2 branch don't have the escape sequence available in implementation of `re`. It seems that you recompile the `re` package from one of those versions.

You may want to compare a few version of `re` package in Python 2.7 and 3.0, 3.1, 3.2. If they don't have much difference, you can use the latest version among them to use as python 2/3.0-3.2 tester. Then add a different tester for python 3.3+ by compiling from 3.3 branch.

**Comment by firasdib** [comment] 2015-01-24 13:02
Ugh, how complicated. I will have to look into this further..

**Comment by firasdib** [comment] 2015-03-22 16:37
Been re-reading the issues. I am running python 2.7 on the site, which does not support `\u`, and to me, it is working as expected. Atleast in the regex tester. Otherwise it could be as @nhahtdh described in the code generator, which I have yet to solve.

**Comment by nhahtdh** [comment] 2015-06-11 05:19
I just edited my comment to correct some inaccurate information.

**Comment by testlnord** [comment] 2015-12-15 09:11
What about adding python2 and python3 flavours? Their behaviour is little different anyway?

**Comment by firasdib** [comment] 2016-07-06 15:57
Fixed in v2

**Closed by firasdib** 2016-07-06 15:57 UTC
Labels: bug, python
