### ISSUE TITLE
Beta: Quick Reference: Scrollbar on QuickRef on larger lists blocks pattern.

### ISSUE THREAD

**Issue by Zarthus** [firasdib/Regex101#555] opened 2016-08-22 10:19 UTC
![http://i.imgur.com/PlvouP9.png](http://i.imgur.com/PlvouP9.png)

Simply select a quickref with a scrollbar (after possibly selecting one without?) and you'll be left with above result.

Chrome 53.0.2785.34 beta-m (64-bit), windows 10

**Comment by firasdib** [comment] 2016-08-22 10:20
OS? Browser? Version?

**Comment by firasdib** [comment] 2016-08-22 15:41
Unable to reproduce, windows 10 Chrome Version 52.0.2743.116 m

You're running a beta, can you verify this exists on stable? Could be a bug in their beta.

**Comment by firasdib** [comment] 2016-08-25 21:31
@Zarthus ping

**Comment by Zarthus** [comment] 2016-08-26 21:43
Issue confirmed to be just for Chrome beta, stable and MS Edge work ifne.

**Comment by firasdib** [comment] 2016-08-27 10:25
It might be worth trying to figure out why its happening. If its a bug in the beta or if the flexbox spec has changed and it will eventually land in stable. 

Is this something you can check for me Jos? If not assign this to someone else. 

Would be much appreciated. 

Mvh Firas

**Comment by Zarthus** [comment] 2016-08-27 10:27
Sorry, I switch to chrome stable entirely because of some of the bugs with chrome beta.

**Comment by nhahtdh** [comment] 2016-08-29 03:52
It's called beta for a reason. I think that we shouldn't support or do testing on beta versions of browsers at all, since the bug may not be there when the stable version is out

**Comment by firasdib** [comment] 2016-08-31 12:14
No way to reproduce or test at the moment, closing for now.

**Comment by Zarthus** [comment] 2016-09-01 21:28
Great news everyone, chrome released a stable upgrade where this issue is reproducible in!

![img](http://i.imgur.com/dbBChrq.png)

Version 53.0.2785.89 m (64-bit)

**Comment by OnlineCop** [comment] 2016-09-01 21:56
http://imgur.com/a/740Up

Top version is Chrome 52. Bottom version is Chrome 53. Exact version numbers are displayed in the gallery below the appropriate picture.

**Comment by firasdib** [comment] 2016-09-03 14:02
I'd like to say this is a bug in chrome. If I remove the `overflow: auto` rule from web inspector and then re-add it, the bug no longer happens.

**Comment by TWiStErRob** [comment] 2016-09-26 10:18
> Simply select a quickref with a scrollbar (after possibly selecting one without?)

@Zarthus [for me](https://github.com/firasdib/Regex101/issues/643) the repro was to select scrollbar'd list after already viewing a scrollbar'd list.

**Comment by firasdib** [comment] 2016-09-28 11:11
Ive submitted a bugreport: https://bugs.chromium.org/p/chromium/issues/detail?id=650999

**Comment by firasdib** [comment] 2016-09-28 11:18
I've also pushed a fix, could you all please confirm its working?

**Comment by TWiStErRob** [comment] 2016-09-28 11:22
Can't repro on either prod nor beta site. Windows 10, Chrome 53.0.2785.116 m (64-bit)
Curious: What did you change?

**Comment by firasdib** [comment] 2016-09-28 12:11
@TWiStErRob Just added height to the parent. No idea why it matters, but fixed it.

**Closed by firasdib** 2016-09-28 12:11 UTC
Labels: beta, bug
