### ISSUE TITLE
A critical error has occurred

### ISSUE THREAD

**Issue by eshmakar** [firasdib/Regex101#1603] opened 2021-06-21 09:05 UTC
## Bug Description
![Screenshot_305](https://user-images.githubusercontent.com/59125020/122736734-00296f00-d289-11eb-9a22-d5b66ebaa9d3.png)

### Browser
Include browser name and version

### OS
Include OS name and version

**Comment by eshmakar** [comment] 2021-06-21 09:06
![Screenshot_306](https://user-images.githubusercontent.com/59125020/122736865-20f1c480-d289-11eb-8831-79beb4d51303.png)

**Comment by working-name** [comment] 2021-06-21 11:14
Hello! Can you please share the URL you were on when this happened or if that's not possible describe what you were doing? In other words, how can we reproduce this?

**Comment by firasdib** [comment] 2021-06-25 09:05
I've seen this multiple times, but I cannot reproduce it. I believe this is an issue with React itself, and is caused by browser extensions that perform DOM manipulation. Since React assumes it has exclusive access to the DOM, any unwarranted changes may cause it to crash like this.

**Comment by skizzo** [comment] 2021-06-28 14:06
This happens every 5 minutes and makes your otherwise great site completely unusable.

**Comment by firasdib** [comment] 2021-06-28 14:12
@skizzo I cannot fix what I cannot reproduce. Does this happen in an incognito window also?

**Comment by working-name** [comment] 2021-07-10 13:36
@eshmakar @skizzo Hello again! Can either of you help us reproduce this issue? Set of steps or a screencast, anything you can do to help is much appreciated.

**Comment by firasdib** [comment] 2021-07-11 15:33
I'm fairly confident this error will not exist in incognito mode. If you can tell me exactly which browser extensions you have enabled, I could try to find out what they are doing, and if any are manipulating the DOM. Then try to mitigate that somehow...

**Comment by working-name** [comment] 2021-09-22 19:30
Closing this for now, please feel free to update the ticket with requested information to help pin point a fix.

**Closed by working-name** 2021-09-22 19:30 UTC
Labels: bug, waiting info
