### ISSUE TITLE
Beta: changing "tabs" greys things out in IE11

### ISSUE THREAD

**Issue by TWiStErRob** [firasdib/Regex101#646] opened 2016-09-26 16:24 UTC
Simply changing between library and editor fades weirdly. Notice that the left menu's opacity or overlay is not at full brightness after clicks, but flashes at full brightness a little.

![](https://cloud.githubusercontent.com/assets/2906988/18842710/4ef89ec4-8416-11e6-80b4-a08ceb1b6b1d.gif)
(ignore the accidental click on chat)

Windows 10, IE11

**Comment by TWiStErRob** [comment] 2016-09-26 16:35
Whoa, this is really inconsistent, it doesn't repro all the time, and when I started to investigate with Developer Tools it started to flash back to normal like nothing happened. Probably a CSS transition bug in IE. Would it bad to disable this fading in `<=IE11` so at least it works as expected even if it doesn't look all that nice?

**Comment by firasdib** [comment] 2016-09-26 16:36
When it happened to me it fixed itself as soon as I interacted with the element. So not worth the time I believe.

**Comment by TWiStErRob** [comment] 2016-09-26 16:40
It's pretty persistent at time, sometimes I can open the dev tools and nothing happens until I select "Inspect element", I can click around all I want, in the library I can even open items, but after closing the popup the grayness stays. The only surefire thing to get rid of it is resizing the whole window so much that it triggers a css media breakpoint.

**Comment by firasdib** [comment] 2016-09-26 18:06
I can not seem to reproduce in my VM at this point. Unless there is an easy fix for this its likely going to remain "broken".

**Comment by TWiStErRob** [comment] 2016-09-26 18:26
I have >90% repro rate of this issue if I start clicking on the editor/library after doing a page refresh. Btw, I'm fine with it being broken, I use Chrome ;)

**Comment by firasdib** [comment] 2017-02-13 12:23
This is a rendering issue with css animations and IE11. Since it affects less than 2.5% of all my visitors (and it seems to be an intermittent issue), I'll close and ask those users nicely to live with their poor web browser choice.

**Closed by firasdib** 2017-02-13 12:23 UTC
Labels: bug, low prio, UX
