### ISSUE TITLE
Substitutions are off screen and no scroll bar on Chrome

### ISSUE THREAD

**Issue by markfaine** [firasdib/Regex101#438] opened 2016-02-22 21:46 UTC
See the attached screenshot:

![regex101-issue](https://cloud.githubusercontent.com/assets/949949/13233832/3c4f7392-d97b-11e5-9bf8-60bb1e9313d8.png)

Chrome Version 50.0.2652.0 dev-m (64-bit)

**Comment by nhahtdh** [comment] 2016-02-23 02:22
I really don't think regex101 should support a version that is currently in development, which is by nature unstable and can contain bugs.

**Comment by OnlineCop** [comment] 2016-02-25 19:13
Duplicate of https://github.com/firasdib/Regex101/issues/423

**Closed by OnlineCop** 2016-02-25 19:13 UTC
