### ISSUE TITLE
Python flavor doesn't recognize multi-digit group references of the form \xx in replacement string

### ISSUE THREAD

**Issue by yanqui-uxo** [firasdib/Regex101#1790] opened 2022-05-02 18:39 UTC
## Bug Description
Same as title, it's parsed as an octal digit in regex101.com, which does not happen in Python when a raw string is used

### Browser
Firefox 99.0.1 (64-bit)

### OS
Windows 11

**Comment by Netxmay** [comment] 2022-06-02 21:40
Hai children of God.any one to show me how regex101 works please

**Comment by firasdib** [comment] 2023-03-04 15:23
I'm unable to reproduce this on the website, perhaps it has been fixed. Closing.

**Closed by firasdib** 2023-03-04 15:23 UTC
Labels: bug, python
