### ISSUE TITLE
Bug: tooltip fails to show on highlighted source white space

### ISSUE THREAD

**Issue by chrisjj** [firasdib/Regex101#743] opened 2016-12-01 11:17 UTC
On https://regex101.com/r/iHEq5l/2 , this tooltip appearing on a Test String region 

![image](https://cloud.githubusercontent.com/assets/6157073/20791967/756abe3c-b7b7-11e6-9a0a-9104b9250b48.png)

fails to appear when the cursor is on the white space in the same Test String region

![image](https://cloud.githubusercontent.com/assets/6157073/20792032/b007a7a8-b7b7-11e6-96f2-95e1dcd77bb4.png)

**Comment by TWiStErRob** [comment] 2016-12-01 11:24
@firasdib #681

**Comment by chrisjj** [comment] 2016-12-01 11:46
Thanks. I see there "That is currently not possible." I can't imagine why its not possible, but I can imagine that any effort might be better put into removing the non-content white space highlight that leads to this issue.

**Comment by TWiStErRob** [comment] 2016-12-01 11:55
The missing hover is a CodeMirror limitation as far as I know. That part of the textarea probably doesn't exist in CodeMirror's model, so there can be no events fired for it. @firasdib is this correct?

Note that the highlight is working as intended. It's a feature not a bug. The highlight is showing you that `\n` is part of the match, without it `A` and `C` would *look like* two separate matches, which is not true. In this simple case it's simple to discern, but in more complex cases it is really useful to see it (e.g. https://github.com/firasdib/Regex101/issues/658#issuecomment-250102545). Read #658 for full discussion.

Try to understand the highlight better, and then you can use it to your advantage when working on the website.

**Comment by chrisjj** [comment] 2016-12-01 12:05
> Note that the highlight is working as intended. It's a feature not a bug. The highlight is showing you that \n is part of the match

My report isn't about the \n that is part of the match. It is about the empty space to the right of the \n (that's misleadingly shown to be part of the match)..

If the intent of highlighting is to show that empty space is part of the match, well that makes no sense to me at all, but that's independent of the issue I am reporting here.

> without it A and C would look like two separate matches, which is not true.

Unfortunately the gap in highlight between A and C does that job already.

> Read #658 for full discussion.

Had already, but thanks anyway for the thought.

> Try to understand the highlight better

Please try to understand that this report is about a fault in the tooltip, not the highlight.

**Comment by Ouims** [comment] 2016-12-01 12:16
Why are you always so wrong and so full of yourself at the same time?
Nobody said you said your report was about \n being matched.
The behavior of the website was explained very carefully to you, read carefully as well.
> Unfortunately the gap in highlight between A and C does that job already.
No, you are wrong again, there is no gap in highlight, the highlight goes to the end of the line and continue from the beginning of the next line, once again you are wrongly taking the vertical gap as a break but guess what, ever since you used a computer in your life, when you select text, 99,99% of the time, a selection which span over multiple lines will show a gap, so why don't you go around and report issue in all the program you use, all the operating system you use and such? GAME ON

**Comment by TWiStErRob** [comment] 2016-12-01 12:19
Yes, I understand that the issue is the hover not showing tooltip. And likely Firas can't do anything about that. I explained the highlight, because you requested "removing the non-content white space highlight".

> Unfortunately the gap in highlight between A and C does that job already.

Exactly! That's the kind of confusion what I mean :) In the above screenshot you have 1 match `A\nC`, if we remove the end-of-the-line highlight, you don't know if `A` and `C` are in the same match or separate matches:
![image](https://cloud.githubusercontent.com/assets/2906988/20793635/40674640-b7c8-11e6-9238-82180c31d7a2.png)

**Comment by chrisjj** [comment] 2016-12-01 12:23
> Nobody said you said your report was about \n being matched.

I can't imagine what else you think this means:

"Note that the highlight is working as intended. It's a feature not a bug. The highlight is showing you that \n is part of the match" https://github.com/firasdib/Regex101/issues/743#issuecomment-264153979

> No, you are wrong again, there is no gap in highlight,

A closer look:

![image](https://cloud.githubusercontent.com/assets/6157073/20793755/95ac8c6c-b7c0-11e6-99b6-7f9687acb15f.png)

> you are wrongly taking the vertical gap as a break but guess what, ever since you used a computer in your life, when you select text, 99,99% of the time, a selection which span over multiple lines will show a gap

Like this, you mean?

![image](https://cloud.githubusercontent.com/assets/6157073/20793803/d5b22c90-b7c0-11e6-9b0f-456726003990.png)

No gap.

**Comment by chrisjj** [comment] 2016-12-01 12:25
> Yes, I understand that the issue is the hover not showing tooltip

Great!

>  I explained the highlight, because you requested "removing the non-content white space highlight" 

Actually no , I didn't. I reckoned that might just cause confusion.

What I said was "any effort might be better put into" it. I'll take care not to say even that next time.

**Comment by Ouims** [comment] 2016-12-01 12:27
It means what it means, it's a note to help you understanding what's happening.
As far as the selection goes, that's part of the 0.1%, i could also show you screenshot about all the others program showing a gap there, but then, you ARE arguing that the vertical gap is the issue?

**Comment by chrisjj** [comment] 2016-12-01 12:30
>As far as the selection goes, that's part of the 0.1%,

I tried also the nearest Windows word processer, text editor and email client. No gap.

> but then, you ARE arguing that the vertical gap is the issue?

THE issue is as per the title "Bug: tooltip fails to show on highlighted source white space".

Shall we stick to that?

**Comment by TWiStErRob** [comment] 2016-12-01 12:57
> I reckoned that might just cause confusion.

Hmm, so the highlight was original added to avoid confusion (my screenshot) and created another type of confusion (this issue) and we've had a confusing discussion about it :).
I think when Firas developed this, he weighed and made an informed decision which confusion is better.

For future reference "Note that ..." and "On a related note:" and friends provides you additional information and understanding about the system, which may not be strictly part of the issue at hand.

> Shall we stick to that?

We can, however that was resolved in the first exchange between us: it's not possible. Just had a quick chat with @firasdib and he confirmed that it's a CodeMirror limitation.

> "any effort might be better put into"

Sorry, I may have misinterpreted that phrase as a passive-aggressive statement to remove a feature. That's why I was trying to explain/defend it.

> Like this, you mean?

I like the screenshot of the text as your counter, however you should note that the text you selected is a single flowing text paragraph, there's no `\n` in it. Chrome textarea behaves the same even if there are new lines, similarly to Sublime as well, but for example IntelliJ IDEA behaves as @Ouims explained:
![image](https://cloud.githubusercontent.com/assets/2906988/20793976/f7dac71a-b7c9-11e6-8469-fe3e809409d5.png)

> Unfortunately the gap in highlight between A and C does that job already.

Do I understand it correctly that you mean that the gap in highlight does the job of separating two matches? If so, it's still a single match based on your OP regex. Note that IIRC gaps between lines were added intentionally to allow space for hover highlight borders, and prevent jumpiness.

**Closed** 2016-12-01 13:11 UTC
Labels: enhancement, UX

**Comment by chrisjj** [comment] 2016-12-01 13:19
> it's not possible. Just had a quick chat with @firasdib and he confirmed that it's a CodeMirror limitation.

Thanks.

So, on the highlight....

>  however you should note that the text you selected is a single flowing text paragraph, there's no \n in it. 

I already noted that thanks. And the fact Oimus' description wasn't specific to the \n case. And the fact it makes no difference in regex101 e.g.

![image](https://cloud.githubusercontent.com/assets/6157073/20795219/db29e634-b7c7-11e6-82dc-954d93272d68.png)

> but for example IntelliJ IDEA behaves as @Ouims explained:

Lost you there. There's no gap, so that's not as Ouims explained: "ever since you used a computer in your life, when you select text, 99,99% of the time, a selection which span over multiple lines will show a gap, so why don't you go around and report issue in all the program you use"

>> Unfortunately the gap in highlight between A and C does that job already.
> Do I understand it correctly that you mean that the gap in highlight does the job of separating two matches? 

No. This was a reference to "without it A and C would look like two separate matches, which is not true."

>  Note that IIRC gaps between lines were added intentionally to allow space for hover highlight borders, and prevent jumpiness.

Thanks. I can't see a need to allow space to hover highlight borders and I can't see what jumpiness a gap avoids, but perhaps that's just me.

**Comment by Ouims** [comment] 2016-12-01 13:57
Well yes, i stand corrected, most program i use don't show a vertical gap.

But I must say, you were explained why the website was behaving that way, yet you came up with:

> If the intent of highlighting is to show that empty space is part of the match, well that makes no sense to me at all, but that's independent of the issue I am reporting here.

There is no other way to put it, you are literally taking us for the dumbest people on earth who don't know what they are doing here, when you clearly are the one not understanding, either that or you are trying to troll. In both case you need to stop.

**Comment by TWiStErRob** [comment] 2016-12-01 14:02
> I can't see what jumpiness a gap avoids, but perhaps that's just me.

You don't see it because it's avoided ;)
Imagine a line has a partial match in the middle and there's no gaps. The match is highlighted with blue background. Now, if you hover on that match you get a brighter blue border.
![image](https://cloud.githubusercontent.com/assets/2906988/20796534/d45af032-b7d6-11e6-9adc-78ea0cad4236.png)
if there was no gap between lines that border would push the lines down, creating a jump when you hover.
To prevent this it's common practice in web development to add a little gap around to make space for the invisible border that becomes visible on hover. Outline is an alternative, which doesn't occupy document space, but it has other limitation which prevents usage.

**Comment by chrisjj** [comment] 2016-12-01 14:13
> You don't see it because it's avoided ;)

:-)

Rephrased: I can't see what jumpiness a gap _that's present_ avoids

> if there was no gap between lines that border would push the lines down,

Oh, that would be bad. Better the border doesn't push anything.
