### ISSUE TITLE
Different result when turning on/off engine optimization in debugger

### ISSUE THREAD

**Issue by nhahtdh** [firasdib/Regex101#333] opened 2015-07-31 05:35 UTC
Regex

```
(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9])(?=.*[,;:])(?=.{8,16})(?!.*[\s])
```

Input string:

```
  Fred:099
```

The regex matches when optimization is disabled and failed when enabled.

![Screenshot](https://cloud.githubusercontent.com/assets/564162/9001377/9f1368d2-3780-11e5-8c24-382b77f23227.png)

Permalink: https://regex101.com/r/bW9fD8/1

(Tested on Firefox 39.0, Chrome 44.0.2403.125)

**Comment by firasdib** [comment] 2015-08-02 16:01
I can't reproduce, can you post a permalink?

**Comment by nhahtdh** [comment] 2015-08-03 08:09
@firasdib Updated the first post with the permalink.

From my investigation, it could be a bug in PCRE, since the regex also fails to match on ideone.

**Comment by firasdib** [comment] 2015-08-03 09:03
Yep, looks like a bug in pcre. Nice.

**Comment by firasdib** [comment] 2016-07-03 23:45
I still believe this bug is active. Have you reported it in the pcre bug tracker?

**Comment by nhahtdh** [comment] 2016-07-04 04:24
No, not yet. Which version of PCRE are you using on regex101 currently? I can't repro on `pcretest` with PCRE 8.38, so I'm not sure how to report to the bug tracker.

**Comment by firasdib** [comment] 2016-07-04 09:56
I'm running an old version, 8.36. If its fixed in 8.38 ill update to that. Thanks

**Comment by nhahtdh** [comment] 2016-07-04 10:34
It does seem to be a bug in some versions. Currently, [ideone has this bug](https://ideone.com/UrbIZ3), and it is [currently using PCRE 8.35](https://ideone.com/EL1yHV).

```
PCRE (Perl Compatible Regular Expressions) Support => enabled
PCRE Library Version => 8.35 2014-04-04
```

**Comment by nhahtdh** [comment] 2016-07-04 10:44
On closer inspection, it seems that [all versions of PHP returns 0](https://3v4l.org/1V2CW) and, even for [the versions with the latest version of PCRE](https://3v4l.org/DvCNW). I can't reproduce this in `pcretest` (with or without "study" option), so I'm not sure where this bug occurs.

**Comment by firasdib** [comment] 2016-07-04 10:48
I've updated to Version 8.39 now, and the bug still exists. But it does not present itself in the same way. The debugger (engine optimizations = 0) will match an empty string (identical to javascript), while the regular matcher will fail outright. This makes me believe its a pre-run check that determines the pattern will never match and immediately returns 0. Feel free to join slack if you wanna chat.

**Comment by firasdib** [comment] 2016-09-06 20:09
See also https://bugs.exim.org/show_bug.cgi?id=1882

**Comment by nhahtdh** [comment] 2016-09-07 04:23
Thanks for filing the bug.

**Comment by firasdib** [comment] 2017-03-11 23:04
I've upgraded to pcre 8.40 now. This should be fixed.

**Closed by firasdib** 2017-03-11 23:04 UTC
Labels: bug, pcre/php, upstream
