### ISSUE TITLE
ABAP Support

### ISSUE THREAD

**Issue by kevinholtkamp** [firasdib/Regex101#1343] opened 2020-07-08 11:38 UTC
It would be cool to have support for the ABAP programming language, since there is a lack of ABAP tools

**Comment by Doqnach** [comment] 2020-07-08 18:55
https://help.sap.com/doc/abapdocu_750_index_htm/7.50/en-US/abenregular_expressions.htm

More or less a duplicate of #165 since ABAP uses POSIX standard for regex.

**Closed** 2021-02-12 16:12 UTC
Labels: duplicate, flavor request
