### ISSUE TITLE
Different matches

### ISSUE THREAD

**Issue by taston** [firasdib/Regex101#625] opened 2016-09-15 12:09 UTC
When I check pattern at regex101 all is good.

But when I check pattern on the server (I have PHP 5) then results are little different.

On regex101 website I use 'gm' modifier.
On server I use 'm' modifier and function `preg_match_all($this->Pattern, $txt, $matches, PREG_SET_ORDER);`

Why it goes wrong?

Can anyone tell me what is propertly php code  to use regexp exactly like regex101? I want get the same result at my page.

**Comment by Ouims** [comment] 2016-09-15 13:19
Hello, did you try using the code generator feature on the left? It should generate proper php code.

**Comment by nhahtdh** [comment] 2016-09-26 08:34
Since there is no reply, I'll close this issue. Feel free to add more information, and I'll reopen this issue once there is enough information to reproduce.

**Closed by nhahtdh** 2016-09-26 08:34 UTC
Labels: no repro
