### ISSUE TITLE
$0 in Javascript flavor substitution sometimes gives random characters

### ISSUE THREAD

**Issue by DinoD123** [firasdib/Regex101#622] opened 2016-09-09 03:40 UTC
If you enter a regular expression with a capturing group, and then repeatedly enter `$0` into the substitution input box, instead of just replacing it with `$0` as it should, sometimes it outputs the first capturing group followed by usually 4 or 5 random alphanumeric characters. To test this, I found that it was easiest to use a regex with a large number of empty capturing groups, e.g. `()()()()()()()()()()()` (for some reason, more capturing groups seems to make it more likely) and repeatedly deleting and typing the `0` from `$0` in the substitution. This doesn't seem to work with all regexes, though, as `(1)(2)(3)(4)` with the test string `1234` sometimes replaces it with nothing (an empty string) for both `$` and `$0`.

System notes:
Firefox 48.0.2
Windows 8.1

**Comment by nhahtdh** [comment] 2016-09-09 06:02
Reproduced in version 1 on same Firefox version Windows 7. Looks like some sort of race condition.

Can't reproduce on version 2 (in private beta). I guess it's probably fixed there.

**Comment by OnlineCop** [comment] 2016-09-15 16:51
Fixed in version 2.

**Closed by OnlineCop** 2016-09-15 16:51 UTC
Labels: bug, javascript
