### ISSUE TITLE
Add support for XRegExp

### ISSUE THREAD

**Issue by slevithan** [firasdib/Regex101#373] opened 2015-09-24 12:27 UTC
I love having the option to switch between PCRE, JavaScript, and Python flavors. What about adding an XRegExp mode as well? https://git.io/xregexp

XRegExp augments JavaScript regex syntax with additional features like named capture, the `x` flag for free spacing and line comments, and `\p{..}` for Unicode properties. Would love to be able to test XRegExp regexes using Regex101, since it would certainly benefit from all the awesome features you've built into Regex101 (match explanation and information, regex formatter and code generator, etc.)

**Comment by nhahtdh** [comment] 2015-09-25 04:34
I think most of those can be emulated with PCRE (well, if your regex doesn't make use of some quirks in JavaScript).

**Comment by slevithan** [comment] 2015-09-25 06:18
That's a good point, at least for the specific features I described. However, there are many other differences between XRegExp and PCRE (some subtle like the ones you mentioned), so having an XRegExp mode that was at least accurate (by getting the flavor quirks and errors right and not allowing features and flags that aren't in XRegExp) but ideally both accurate and complete (including the XRegExp features that aren't in PCRE) would still be a huge advantage for XRegExp users. Or to put it another way, it would make Regex101 by far the most advanced XRegExp tester.

Supporting XRegExp in Regex101 would also offer JavaScript developers a path to be able to take advantage of more of Regex101's advanced features, should they choose to use XRegExp in order to access those features.

**Comment by OnlineCop** [comment] 2015-10-23 16:29
Duplicate of #222

**Closed** 2015-11-04 08:22 UTC
