### ISSUE TITLE
Suggestion: make a complex regex more readable

### ISSUE THREAD

**Issue by jeromectm** [firasdib/Regex101#1448] opened 2020-12-24 14:06 UTC
A suggestion to make a complex regex more readable: display it in multiple lines, by moving the content of each group (either parenthesis or bracket) to the next line. An example to illustrate what I mean:
`(.*)(?:(?: \((?:.+, )?)|(?:(?<!,)[ _\.\(\)\[\]\-]+))(19\d\d|20[0-2][0-9])((\)[^\(\)]*\.)|([ _\,\.\(\)\[\]\-][^0-9]|$))`
could be displayed as:
```
(  )(?:                |                           )(      |            )(              |                            )
 .*    (?:            ) (?:                       )  19\d\d 20[   ][   ]  (            ) (                        | ) 
           \((?:    )?     (?<! )[              ]+             0-2  0-9    \)[^    ]*\.   [                ][^   ] $  
                .+,            ,   _\.\(\)\[\]\-                               \(\)         _\,\.\(\)\[\]\-   0-9     
```

**Comment by Doqnach** [comment] 2020-12-24 14:17
It is already possible to do this yourself using the "e*x*tended" flag.

https://regex101.com/r/SJM9KH/1

The only thing it doesn't do is any "auto-formatting" because this would get really complex (and intensive) to get right for all use-cases.

**Comment by jeromectm** [comment] 2020-12-24 14:25
Thanks for the fast answer :-)
I was thinking of an automatically decomposed view of the regex, in the explanation pane, rather than manual formatting.

**Comment by working-name** [comment] 2020-12-27 17:40
Related: #1283

**Comment by firasdib** [comment] 2021-02-12 12:27
Dupe of #1283  - continue the discussion there!

**Closed by firasdib** 2021-02-12 12:28 UTC
Labels: feature request
