### ISSUE TITLE
Python regex shows match when there is none (low priority)

### ISSUE THREAD

**Issue by bivald** [firasdib/Regex101#992] opened 2018-04-12 18:58 UTC
Hi,

A colleague of mine wrote the following python flavored regex:

`(?P<prefix>[ABC]{3}|[Abc]{3}|[AB]{2})( |)|(?P<digits>[0-9]{3})`

It needs refactoring, but when doing so I found that while the above regex matches with input "Abc123" in regex101 (and returns `123` as `digits`) in reality Python doesn't agree. 

```bash
python -c "import re; print re.match('(?P<prefix>[ABC]{3}|[Abc]{3}|[AB]{2})( |)|(?P<digits>[0-9]{3})', 'Abc123').groupdict()"
# {'digits': None, 'prefix': 'Abc'}
```

```bash
python3 -c "import re; print(re.match('(?P<prefix>[ABC]{3}|[Abc]{3}|[AB]{2})( |)|(?P<digits>[0-9]{3})', 'Abc123').groupdict())"
# {'prefix': 'Abc', 'digits': None}
```

As I said, the regex needs refactoring due to it's heavy (and slightly odd) use of |. I'm entering it as an issue simply in case you would find it interesting.

PS: Great service! Keep up the good work!

**Comment by Doqnach** [comment] 2018-04-13 07:24
Duplicate of #978

**Comment by firasdib** [comment] 2018-05-15 20:03
Does `re.match` perform a global search?

**Comment by ashemedai** [comment] 2018-06-20 11:07
From the documentation:

> If zero or more characters at the beginning of string match the regular expression pattern, return a corresponding match object. Return None if the string does not match the pattern; note that this is different from a zero-length match.
> 
> Note that even in MULTILINE mode, re.match() will only match at the beginning of the string and not at the beginning of each line.
> 
> If you want to locate a match anywhere in string, use search() instead.
>

**Comment by firasdib** [comment] 2018-08-05 13:50
It would seem that if you just remove the global flag, the behavior is as expected.

**Closed by firasdib** 2018-08-05 13:50 UTC
Labels: bug
