### ISSUE TITLE
Cannot edit script after clicking group

### ISSUE THREAD

**Issue by Cjstoney** [firasdib/Regex101#1705] opened 2022-01-21 19:36 UTC
## Bug Description
After clicking one of the groups under the Match Information panel, User cannot access click into the regular expression input box. 

### Reproduction steps
Using Javascript Flavor, enter a regular expression and test string that contains matches. Click on one of the groups in the Match information panel. Then attempt to click back into the regular expression input box. 

### Expected Outcome
Should be able to click back into the input box to alter the regular expression. 

### Browser
Google Chrome Version 97.0.4692.71 (Official Build) (x86_64)

### OS
MacBook Pro, macOS Monterey version 12.1

**Comment by firasdib** [comment] 2022-01-21 20:46
Interesting. I wonder if this isn't a regression with Codemirror. I can reproduce on Manjaro at least.

**Comment by firasdib** [comment] 2022-01-21 21:17
Looks like an error on my part.

I've pushed a fix, give it 5-10 min and try again. Please confirm if it works for you afterwards.

**Closed by firasdib** 2022-01-21 21:17 UTC
Labels: bug

**Comment by Cjstoney** [comment] 2022-01-21 21:52
The fix seems to have worked. Thanks!
