### ISSUE TITLE
Substitution doesn't update

### ISSUE THREAD

**Issue by Cazra** [firasdib/Regex101#667] opened 2016-09-30 19:54 UTC
When I enter text into the Test String area, the Substitution area isn't getting updated anymore. It just stays blank.

This behavior is happening on Chrome 49.0.2623.87, running on OSX. It is also happening on Safari.

**Comment by critmcdonald** [comment] 2016-09-30 19:57
I've confirmed this problem, too, after a couple of students hit it, but for me it was in Safari on Mac. Chrome was fine. Firefox gave me and INCORRECT substitution.

![screen shot 2016-09-30 at 2 55 10 pm](https://cloud.githubusercontent.com/assets/4553750/19005026/2be7ab68-871e-11e6-8b89-851f29e17de7.png)
![screen shot 2016-09-30 at 2 55 03 pm](https://cloud.githubusercontent.com/assets/4553750/19005025/2be5e88c-871e-11e6-9448-6a59d2b552a3.png)

**Comment by TWiStErRob** [comment] 2016-09-30 20:21
@critmcdonald what is incorrect there? The match is `\0`=`this` and you're replacing it with `\1`=`his` the rest is not part of the match so it's left alone.

**Comment by firasdib** [comment] 2016-09-30 21:02
I'm unable to reproduce the issue. Here is a permalink I created: https://regex101.com/r/tylTyS/1

What browser and OS are you using?

**Comment by firasdib** [comment] 2016-10-05 14:29
Closing this. If you still think there is a bug, please reopen.

**Closed by firasdib** 2016-10-05 14:29 UTC
Labels: no repro, waiting info
