### ISSUE TITLE
Quick Reference on 4:3 screen

### ISSUE THREAD

**Issue by qpmm** [firasdib/Regex101#1006] opened 2018-05-26 15:28 UTC
I have a 4:3 17" monitor with 1280x1024 screen resolution. It's really tough to use Quick Reference as it is so much shrinked and there isn't any scrollbar, any splitter, any mouseover hint, etc.

**Comment by JMichaelTX** [comment] 2018-05-26 22:11
Even though I have a much larger screen, I would much prefer to have the Quick Ref open as a separate window, that I can resize.  Sometimes I need to scroll though a number of items to find the one I want.  The auto-sizing of one main window really gets in the way.

**Comment by Doqnach** [comment] 2018-05-29 08:48
I don't think a separate window/browser tab would work well for most people.

But how about a button to maximize the/any pane to a 'fullscreen' modal overlay?

**Comment by TWiStErRob** [comment] 2018-05-29 09:33
@qpmm just to clarify: you're talking about lack of horizontal scrollbar at the right side of quick ref and ellipses of those items, right? @firasdib I think a simple `title="contents"` on the ellipsised `li` would help?

**Comment by Zarthus** [comment] 2018-06-02 15:04
Duplicate of: https://github.com/firasdib/Regex101/issues/639

Mild relevance (I think): https://github.com/firasdib/Regex101/issues/916

**Comment by firasdib** [comment] 2018-06-03 18:02
I've added the `title` field for now.

**Comment by firasdib** [comment] 2018-11-27 09:33
Another option is to "always collapse right sidebar" and open it that way instead. Then you'll have a much larger viewing area.

**Closed by firasdib** 2018-11-27 09:33 UTC
Labels: duplicate, feature request
