### ISSUE TITLE
Named group captures, but does not substitute in the else part of the if-then-else construct.

### ISSUE THREAD

**Issue by HYBRID-BEING** [firasdib/Regex101#243] opened 2015-02-12 23:03 UTC
https://www.regex101.com/r/iH1dP4/2

**Comment by nhahtdh** [comment] 2015-02-13 07:48
Duplicate of https://github.com/firasdib/Regex101/issues/216

Even if it is fixed, it is useless, since PHP doesn't support reference to named group in replacement string.

**Closed** 2015-03-22 13:52 UTC
