### ISSUE TITLE
entry save / edit tags

### ISSUE THREAD

**Issue by ltdeta** [firasdib/Regex101#452] opened 2016-03-17 14:22 UTC
how can i delete tags ?
the input field for tags is not really intuitively ...

**Comment by Zarthus** [comment] 2016-03-24 09:29
Could you elaborate more on your issue?

**Comment by ltdeta** [comment] 2016-03-24 19:02
I test it on my ipadand it works as desired
I will test ist on my pc again later

**Comment by nhahtdh** [comment] 2016-04-13 02:45
I will close this issue for now. Will reopen when the issue is clarified.

**Closed by nhahtdh** 2016-04-13 02:45 UTC
Labels: no repro
