### ISSUE TITLE
Wrong highlights if the teststring wraps to a new line

### ISSUE THREAD

**Issue by MuchoGrande3** [firasdib/Regex101#588] opened 2016-08-25 20:59 UTC
I was testing a rather simple regex but got weird highlighted matches in my teststring. After playing around a bit i noticed that it only happens after the string wrapped to a new line. I think this is just a bug in the display of the matches.
Here is the Saved regex: https://regex101.com/r/zW3kR6/2
And two screenshots:
![screenshot from 2016-08-25 22-43-24](https://cloud.githubusercontent.com/assets/19548558/17985675/22990dea-6b17-11e6-9562-d515fd4c6825.png)
![screenshot from 2016-08-25 22-43-47](https://cloud.githubusercontent.com/assets/19548558/17985731/5b4ee0a6-6b17-11e6-8089-6808a8e3562a.png)
The first screenshot shows the wrong higlights.
I don't know, how bad this bug is, but i confused me a bit.

**Comment by nhahtdh** [comment] 2016-08-26 04:07
Duplicate of  #321, #351, #489, #529, #541. Should have been fixed.

**Closed by nhahtdh** 2016-08-26 04:07 UTC

**Comment by MuchoGrande3** [comment] 2016-08-26 06:41
Ah, sorry. I only looked at the open bugs. Will check more thoroughly the next time.

**Comment by firasdib** [comment] 2016-08-26 08:01
Sorry about this @MuchoGrande3. Its fixed in the new version, which is currently being beta tested. I expect us to be done and able to release in a week or two!
