### ISSUE TITLE
Matches in RTL text don't get properly highlighted

### ISSUE THREAD

**Issue by sixtyfive** [firasdib/Regex101#838] opened 2017-04-13 16:32 UTC
Consider [this regex](https://regex101.com/r/WqQ6un/2). It correctly matches everything it's supposed to match (mostly 4-letter active participles) and correctly shows these matches in the "Match information" pane. What does not work is highlighting of these same matches in the "Test string" box.

Screenshot (Debian 9, Gnome, ungoogled-chromium):
![2](https://cloud.githubusercontent.com/assets/192860/25014280/5d6ecf70-2077-11e7-920a-2c4fa2b9d331.png)

Copying the regex into Gedit gives an idea of what it should look like. Screenshot:
![3](https://cloud.githubusercontent.com/assets/192860/25014327/91d40cda-2077-11e7-97e3-a67b20143481.png)

I'd be happy to provide more information, please let me know what you need!

**Comment by firasdib** [comment] 2017-04-14 08:40
Duplicate of https://github.com/firasdib/Regex101/issues/764

**Closed by firasdib** 2017-04-14 08:40 UTC
