### ISSUE TITLE
[BUG][FR] SED doesn't support lookaheads/lookbehinds.

### ISSUE THREAD

**Issue by leonhma** [firasdib/Regex101#1634] opened 2021-08-08 11:14 UTC
## Bug Description
The code generator for sed happily puts the lookahead in the `sed -e` field. Sed doesnt support lookaheads.

### Reproduction steps
`sed -E 's/ (?=\d)/|/g;t;d' <<< "Minimum required versions: 3.7
Incompatible versions:     2"`
in bash

### Expected Outcome
error was expected (or use perl re)

### Browser
chrome

### OS
ubuntu in WSL

### Suggestion

Name the code generator `bash`. Dynamically decide which tool to use (or just use `perl`).

**Comment by working-name** [comment] 2021-08-08 21:28
Hello there,

This is not a bug, it's intended behavior - the site should not touch the regex you wrote. Therefore, the code generator is not meant to adapt/rewrite a regex to match the target limitations/features, it only tries to give an example of how you would implement your regex in whatever language you choose. The only thing it tries to do for you is properly escape the regex for that language.

**Comment by leonhma** [comment] 2021-08-09 13:46
Shouldn't it inform you that sed doesn't support lookaheads?

**Comment by working-name** [comment] 2021-08-09 20:05
I'm not sure if it should, it relies upon you knowing the target for which you write the regex. Maybe this could be considered if/when a sed flavor is implemented, but as it stands this feature would be marginally useful, catering only to those who do not know enough about regex to differentiate between flavors. There are volunteers on IRC in the regex channel (you can get to it by clicking the live help icon) who are more than happy to help with any regex questions, often supplying working solutions tailored to the flavor you wish to work with.

For the moment, I'm afraid that outside of live help, the other option I can think of is reading the sed documentation and sticking to the types of tokens it understands:
https://www.gnu.org/software/sed/manual/html_node/Regular-Expressions.html

**Comment by working-name** [comment] 2021-08-14 19:58
Closing for now.

**Closed by working-name** 2021-08-14 19:58 UTC
Labels: bug, invalid
