### ISSUE TITLE
In test string matches out of place

### ISSUE THREAD

**Issue by Redominus** [firasdib/Regex101#2051] opened 2023-04-25 15:26 UTC
## Bug Description
Blue rectangle marking the matches is out of place on test strings. 

### Reproduction steps
Using the following saved regex
https://regex101.com/r/uj4uL4/1
* Jump to the latest matches.
* Should be out of place
* Scrolling a bit up and down make it worst
![image](https://user-images.githubusercontent.com/22024214/234325951-ec189f27-c243-46c0-99f6-dd02d70839f3.png)

### Expected Outcome
Blue rectangles should be behind the matched strings

### Browser
Brave Browser v1.50.125. Chromium 112.0.5615.165
Google Chrome Version 112.0.5615.165 (Official Build) (64-bit)

### OS
Ubuntu Budgie 22.04.04

**Comment by firasdib** [comment] 2023-04-26 07:41
Thank you for reporting this.

I was hoping this would be uncommon, but perhaps it's not ...

This is a bug in Codemirror v6, and I have made the author of the library aware of it, but as of right now, there does not seem to be any fix, and the issue is not being prioritized.

You can read more here: https://github.com/codemirror/dev/issues/1089 - hopefully enough attention can be brought for the author to look into it again.

**Comment by firasdib** [comment] 2023-08-04 10:46
I've managed to fix this with the help of @marjinh. Thank you both! This will be included in the next release.

**Closed by firasdib** 2023-08-04 10:46 UTC
Labels: bug, upstream
