### ISSUE TITLE
Extended_Pictographic unicode property missing (probably others as well)

### ISSUE THREAD

**Issue by alystair** [firasdib/Regex101#1524] opened 2021-03-08 04:51 UTC
## Bug Description
Service doesn't accept newer unicode properties such as Extended_Pictographic, Emoji, etc.

### Reproduction steps
`/\p{Extended_Pictographic}/ug`

### Expected Outcome
To work, so I can test emoji capture.

### Browser
Chrome Stable 88.0.4324.190 (Official Build) (64-bit)

### OS
Windows 10 Pro 21H1

**Comment by firasdib** [comment] 2021-03-08 20:53
Thanks, I'll try to get this fixed asap.

**Comment by alystair** [comment] 2021-03-08 21:43
Super appreciate it - regex101 is one of the top external resources I actively use as well as provide others <3

**Comment by firasdib** [comment] 2021-03-10 19:46
Should be fixed now!

**Closed by firasdib** 2021-03-10 19:46 UTC
Labels: bug

**Comment by Ouims** [comment] 2021-03-11 17:07
@firasdib, yesterday, @alystair joined \#regex and asked a question which involved this \p.


I found some issues with it: https://regex101.com/r/OwAU54/2
(Note: the test string is not mine, it's @alystair's, and i use the option to visualize whitespace etc)

According to the doc, this \p matches one character, and one character only.

Let's mention the first group of emoticon after "BUG: " and before "appears"

It starts with two surrogates: 55357 and 56902 in decimal, which forms the codepoint 128582 in decimal, which matches

- The editor does not render this code point correctly, the match info panel does.

Then, it has another two surrogates, 55356 and 57342, which forms the codepoint 127998

- This code point is not rendered at all in the editor (the js engine/pattern does not seem to match that codepoint, no idea if it's correct at this point)

Then there's an zero width space, code point 8205 (no match), then there's the code point 9792, which matches and shows correctly in both in editor and match info panel.

Then a 'zerowidth mark' code point 65039 (no match) and there's two more pairs of surrogates, rendering two code points, which matches and display fine.

Others mentions: the highlighting colors for the match are not alternating, which makes it looks like the match consists of multiple characters, which was super confusing for @alystair's question.

I've seen more issues but they are most likely related to the above, I'll check more once this gets fixed.

**Comment by alystair** [comment] 2021-03-22 01:12
Maybe better to open a new issue instead

**Comment by Doqnach** [comment] 2021-03-22 07:46
@Ouims please open a new issue indeed. This one has already been closed.

**Comment by Ouims** [comment] 2021-03-22 19:17
@alystair @Doqnach, all issues which get a reply after they get closed get seen and replied to by @firasdib, i'm there to observ it, the problem is not reopening an issue, the issue 400% belong to this thread anyway, it's completely related to the implem of that \p
