### ISSUE TITLE
Keyboard auto-complete failure

### ISSUE THREAD

**Issue by he852100** [firasdib/Regex101#1314] opened 2020-04-23 02:19 UTC
## Bug Description
The cursor deviates from the correct position.

![out](https://user-images.githubusercontent.com/26913892/80051796-a2e24280-854b-11ea-9f04-ee8060d9b7f6.gif)

### Browser
Include browser name and version

chrome
### OS
Include OS name and version

android

Input:

讯飞
百度

**Comment by working-name** [comment] 2020-04-24 06:11
I'm unable to reproduce the bug on Chrome 81.0.4044.117 on Android 9. I also do not get that input keyboard by default. That may be the cause of the problem. Switch to stock keyboard and see if you can still reproduce it. 

The only thing I see is the mode lagging behind input - sometimes a metacharacter will appear back after I removed it as the mode finishes its parsing. That could be my slow device or the extent of CM's performance on a mobile platform. However, cursor does not jump around.

Keep in mind, CodeMirror's mobile support is fragile and very new. Incidentally CM6 is under development which will play with mobile browsers in a more native way.

**Comment by he852100** [comment] 2020-04-24 06:23
It needs to jump to the right place。On this page, it always appears in the wrong place
![20200424_142146](https://user-images.githubusercontent.com/26913892/80181303-288eec80-8637-11ea-84bf-7ed9946e7dff.gif)

**Comment by working-name** [comment] 2020-04-24 14:16
Here's some homework for you:

1. Try inputting brackets with a stock android keyboard and report whether you still experience the bug
2. Try your fancy keyboard here: https://codemirror.net in the code editor and report whether you experience the same bug
3. Explain what "right place" means to you. Where does the cursor go when you use this fancy keyboard in a regular textarea?

**Comment by he852100** [comment] 2020-04-24 14:21
In response, I have already demonstrated.It will be in this correct position[|]

**Comment by he852100** [comment] 2020-04-24 14:29
I understand that you want me to use [ or ] a single input, but I will not do so.
The action of entering two simultaneously may be: [ + ] + ←

**Comment by working-name** [comment] 2020-04-24 16:46
So far in my mind you've already proven that CodeMirror is not happy with your fancy keyboard, but if you really want to make 100% sure, try your keyboard on codemirror.net like I said. If you find the behavior to be the same, then you're probably better off going to the source: https://github.com/codemirror/CodeMirror/issues

I'll be closing this for now, as this is likely an upstream issue. Please reopen if deemed necessary.

**Closed by working-name** 2020-04-24 16:46 UTC
Labels: bug, waiting info
