### ISSUE TITLE
Caret disappear in regexp field when positioned on group (Chrome on Mac)

### ISSUE THREAD

**Issue by cigno5** [firasdib/Regex101#928] opened 2017-10-20 07:42 UTC
The caret disappear when inside a group, and it makes very annoying moving through the regexp without using the mouse. 

The caret is still visible when outside:
```
.+((foo)$)
   ^
   here the caret is still visible, moving to the right it disappear
```

I'm using mac os X 10.11.6 with Chrome 61.0.3163.100. 
Using Firefox it works fine

**Comment by Doqnach** [comment] 2017-10-23 08:10
I don't experience this. OSX 10.13, Opera 48 (equivalent to Chrome 61.0.3163.100)

**Comment by cigno5** [comment] 2017-10-23 08:30
It's weird. I have even disabled all plugins and reload. I'm logged in and I'm using 'python' regexp with "g" flag.

**Comment by firasdib** [comment] 2017-10-23 08:33
I tried it too but can't reproduce it. OSX `Version 61.0.3163.100 (Official Build) (64-bit)`

**Comment by cigno5** [comment] 2017-10-23 08:44
I have the same behaviour with Chrome `62.0.3202.62 (Official Build) (64-bit)`

Trying to find out some more clues I've noticed that

```html
<div class="CodeMirror-cursors" style="">
    <div class="CodeMirror-cursor" style="left: 349.757px; top: 0px; height: 20px;">&nbsp;</div>
</div>
```
is constantly flipping between `style=""` and `style="visibility: hidden"`, but this happens also when the caret is visibile.

**Comment by firasdib** [comment] 2017-10-23 08:46
@cigno5 That is by design, the caret is just a div that switches between visible and hidden to simulate blinking.

**Comment by cigno5** [comment] 2017-10-23 08:54
Ok, I've guessed that, and if I change the `&nbsp;` with the pipe symbol ( `|` ) I can see it "blinking".

It has to be something internally to Chrome then, somehow it doesn't show the caret in my situation. I don't know where to look for (by the way, really good job, I love the interface and its features!)

**Comment by firasdib** [comment] 2017-10-23 08:58
> Ok, I've guessed that, and if I change the &nbsp; with the pipe symbol ( | ) I can see it "blinking".
> 
> It has to be something internally to Chrome then, somehow it doesn't show the caret in my situation. 

Its weird, could be a bug with CodeMirror itself. I have not been able to fix many bugs or update dependencies for a while as I'm swamped with personal stuff. Hopefully its not too limiting.

> (by the way, really good job, I love the interface and its features!)

Thank you!

**Comment by firasdib** [comment] 2017-12-06 09:10
Can't reproduce, so closing for now.

**Closed by firasdib** 2017-12-06 09:10 UTC

**Comment by cigno5** [comment] 2017-12-06 09:11
The problem is now fixed, probably Chrome updated! Thank you!
