### ISSUE TITLE
False error detected for '/' in pattern

### ISSUE THREAD

**Issue by David263** [firasdib/Regex101#1568] opened 2021-04-23 23:18 UTC
## Bug Description
An error is reported by Regex101 for patterns that match '/' at any character position.

### Reproduction steps
Enter a pattern that must match a slash character. No test case is needed.

### Expected Outcome
Should not detect an error, because PHP preg_quote('/') returns '/', not '\\/'.

Regex101 reports error '/ An unescaped delimiter must be escaped with a backslash (\\)", which is a completely incorrect statement if it is interpreted as always being the case for '/' as a delimiter character regardless of the pattern delimiter.

Note: The pattern delimiter characters are fixed as using '/'. A really good fix for this bug would be to use '/' when the pattern itself doesn't include a '/', otherwise use any character that does not occur in the supplied pattern. PHP supports and requires the specification of the delimiter characters as part of the pattern argument.

### Browser
Include browser name and version
FF 88.0/64
### OS
Windows 10, latest stable update.

**Comment by working-name** [comment] 2021-04-23 23:34
Hi David,

Please correct me where I'm wrong:

1. If this is a bug report about an erroneous message to escape `/` in the pattern while `/` happens to be the regex delimiter, then I'm afraid it's not a bug. It's something that [php itself](https://www.ideone.com/pvGf4z) would also instruct.
 - `preg_quote()` does indeed return `\/` for `/` - see [documentation example 1](https://www.php.net/manual/en/function.preg-quote.php).
 

2. If this is a feature request to automatically switch delimiter to avoid clashing with tokens in the pattern then that in my humble, non-developer opinion might be a complex task, prone to errors. But I can't speak for the developer.

**Comment by David263** [comment] 2021-04-23 23:41
working-name, Your statement contains an error. Did you actually run preg_quote?

The documentation page you cite says "Note that / is not a special regular expression character. "

What that means is that '/' does **not** have to be escaped.

**Comment by working-name** [comment] 2021-04-23 23:45
@David263 I did it in the same test case on https://www.ideone.com/pvGf4z

The function itself takes a second parameter called `delimiter`, which in this case is `/`. Perhaps we're talking different delimiter than `/` itself?

**Comment by working-name** [comment] 2021-04-23 23:47
Here's a gotcha that may have fallen through the cracks: if you're switching flavors from one to another, the delimiter will then reset back to `/` which could lead to the persistent error you describe.

**Comment by David263** [comment] 2021-04-24 01:06
Never switch back to the initial default. It makes using the tool harder to use. Save the pattern delimiters and the modifier flags and keep them the same. I always use modifiers "s", so changing to "gm" is quite a problem. And I usually use ~ or @ as my pattern delimiter, **never /** because it is so common. Even better, require **an entire pattern string**, such as @\w+@s , not just \w+ .

**Comment by working-name** [comment] 2021-04-24 13:25
You may wish to file a feature request for "don't reset my delimiter when switching between PCRE versions" but having that applied globally is probably impractical as some languages do not support any other delimiter than `/` or they have an entirely different delimiter. Then there is variation within the same language to worry about, i.e. you can write a regex by just quoting it, no delimiters.

As far as flags go, it's a similar process. If you use `/s` it will carry over to every other flavor that you switch to, so long as the newly selected flavor supports it. If it does not, it's removed. Try it out with the `/x` flag for example.

You are not limited to pasting just the "stuff" between delimiters, you can paste the whole regex with your custom delimiter and it will be parsed accordingly, of course, if the flavor you selected supports it.

**Comment by David263** [comment] 2021-04-24 15:05
"you can paste the whole regex with your custom delimiter and it will be parsed accordingly, of course,"

That did not happen. My pattern was "&abc&", test string was "abc" and result was "Your regular expression does not match the subject string."

The reason? My last chosen pattern delimiters ("@") were exserted around the pattern!

My Options were: PHP > 7.3 and Match function.

I think your supplying the pattern delimiter and the modifier flags and **requiring** the user to choose them properly is a problem. That part of the interface should be changed so that all that information is **required** to be pasted or typed by the user.

**Comment by working-name** [comment] 2021-04-24 15:26
Although many characters can be delimiters it would be very impractical to list them in that pop-up for the flags. So try that paste again with an available delimiter (from the list). 

But there's no double request here. You either paste something the site understands and it does its parsing job, or it doesn't touch your paste and lets you figure out what might be good as a second-choice, i.e. switching from using `&` to using `@`.

Maybe there's room for change here - switching to manual input and taking the first character as the delimiter for the regex, but the developer would have to assess and decide if the effort is warranted. I can see a few issues arising from this including expecting the site to work with `r"..."` and other interesting prefixes some languages use.

Your suggestion below should probably be turned into a feature request.

> I think your supplying the pattern delimiter and the modifier flags and requiring the user to choose them properly is a problem. That part of the interface should be changed so that all that information is required to be pasted or typed by the user.

**Comment by working-name** [comment] 2021-04-25 17:02
Closing in favor of #1569.

**Closed by working-name** 2021-04-25 17:02 UTC
Labels: bug, discussion, invalid, no repro
