### ISSUE TITLE
Add flavour "egrep"

### ISSUE THREAD

**Issue by chrisblech** [firasdib/Regex101#846] opened 2017-05-07 05:51 UTC
I use you great tool to design/test rules for the unix-tool "[logcheck](http://logcheck.org)", which uses internally unix command "[egrep](https://wiki.ubuntuusers.de/grep/)".
Most times I achive best results using your flavour "golang", but it seems not to be exact the same. For example, the shortcut `\d` will not be accepted/translated by unix egrep.

So could you please implement the flavour "egrep" natively in your tool ?

**Comment by Zarthus** [comment] 2017-06-15 20:24
Duplicate of https://github.com/firasdib/Regex101/issues/165? Is egrep different from posix-extended?

**Comment by cheako** [comment] 2017-09-23 17:17
Please close to avoid confusion.

**Closed** 2017-09-23 19:12 UTC
Labels: flavor request
