### ISSUE TITLE
PHP Generated Code Escaped Incorrectly

### ISSUE THREAD

**Issue by cjbarth** [firasdib/Regex101#287] opened 2015-05-19 15:59 UTC
I recently encountered this generated code from your tool:

$re = "/(\\%(\\d)\\$s)/"; 
$str = "Synchronized from: %1\$s %2\$s"; 
$subst = "<span class=\"token\">{Token $2}</span>"; 
 
$result = preg_replace($re, $subst, $str);

That code don't work because double quotes (" ") are how to define a 'magic string' in PHP. Thus, PHP attempts to replace the $s in $re, $str, and the $2 in $subst with a value for those variables, which could be anything, and in my code-base was something that introduced a syntax error to the preg_replace. Once I changed the outer double quotes to single quotes thing started working better.

However, there was still an issue. I had entered into the UI to have a replacement string of "<span class="token">{Token $2}</span>", as you can see, without the " escaped. Since you had nested " it made sense that you escaped it in your string, however, when done correctly, that is to say using a single quote (' ') around the string, the escape symbols for the " started being included in the string, which obviously caused HTML errors in my intended use.

https://regex101.com/r/vH8bT6/1

**Comment by firasdib** [comment] 2015-05-20 21:37
Not sure I follow, whats wrong with this code?

````
$re = "/(\\%(\\d)\\$s)/"; 
$str = "Synchronized from: %1\$s %2\$s"; 
$subst = "<span class=\"token\">{Token $2}</span>"; 
 
$result = preg_replace($re, $subst, $str);
````

**Comment by nhahtdh** [comment] 2015-05-21 04:37
The problem is `$s` can be interpolated.

**Comment by firasdib** [comment] 2015-05-21 07:04
I thought it was escaped?

**Comment by nhahtdh** [comment] 2015-05-21 07:17
@firasdib See http://ideone.com/adjF21

You probably need to escape `$` once more, if you want to use double quoted string. I'm not sure about all the rules, though.

The better solution is to use singly-quoted string, where variables are not interpolated and the escape rules are extremely simple.

**Comment by firasdib** [comment] 2016-07-05 19:57
Should be fixed in v2. Will go through rigorous testing.

**Closed by firasdib** 2016-07-05 19:57 UTC
Labels: bug, pcre
