### ISSUE TITLE
Quizz - Test 3 - Uppercase Consonnants

### ISSUE THREAD

**Issue by eric13500** [firasdib/Regex101#1727] opened 2022-02-26 14:06 UTC
## Bug Description
RegEx fonctionnelle non reconnue

RegEx : [A-DF-HJ-NP-TV-Z]

Résultat : _Test 6/10: You seem to be counting vowels too. A gentle reminder: aeiou are vowels._

Test dans le simulateur : 
REgEx : ([A-DF-HJ-NP-TV-Z])

Chaîne de test : 
ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!:;,?./

Liste :
Substitution : $1
Résultat : ABCDFGHJKLMNPQRSTVWXYZ

### Expected Outcome
Validation de ma réponse, et meilleure solution si elle existe.

### Browser
Chrome à jour

### OS
Windows 10 Pro

Merci pour votre travail !

**Comment by working-name** [comment] 2022-02-26 14:15
Hi @eric13500 if you're able to, please keep it in English. Just FYI, we do not give out solutions to the quiz to avoid spoiling it for others. 

That being said, this is not a bug, you need to read the hint closely.

**Comment by working-name** [comment] 2022-03-04 02:44
Closing this for now, please feel free to continue the conversation, we'll open it back up if necessary.

**Closed by working-name** 2022-03-04 02:44 UTC
Labels: bug, invalid, quiz
